import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { supabase } from '../../lib/supabaseClient';
import { api } from '../../lib/api';
import { useAuth } from '../../lib/auth/AuthContext';
import { cardStyle } from '../../lib/cardStyle';

interface ChildRow { id: string; name: string; grade_level: number; username: string; }
interface RosterRow { id: string; student_id: string; assigned_at: string; children: ChildRow | null; }
interface StudentProgress { child_id: string; level: string; accuracy_sum: number; total_attempts: number; activities_completed: number; streak: number; }
interface StudentSession { word: string; accuracy_percentage: number; is_correct: boolean; created_at: string; }
interface StudentAssignment { id: string; status: string; due_date: string | null; pdf_materials: { title: string } | null; }
interface StudentModule { id: string; module_number: number; title: string; state: 'locked' | 'unlocked' | 'completed'; content_item_count: number; completed_content_item_count: number; }
// Ten cards keep each class-list page scannable while avoiding overly frequent
// navigation for a typical teacher roster.
const ROSTER_PAGE_SIZE = 10;

export default function MyStudents() {
  const { user } = useAuth();
  const [gradeFilter, setGradeFilter] = useState('all');
  const [rosterSearch, setRosterSearch] = useState('');
  const [selectedStudentId, setSelectedStudentId] = useState<string | null>(null);
  const [rosterPage, setRosterPage] = useState(1);
  const { data: teacherProfile } = useQuery({ queryKey: ['teacher-profile', user?.id], queryFn: async () => { const { data, error: err } = await supabase.from('teacher_profiles').select('grade_levels').eq('user_id', user!.id).maybeSingle(); if (err) throw err; return data as { grade_levels: number[] } | null; }, enabled: Boolean(user) });
  const gradeLevels = teacherProfile?.grade_levels ?? [];
  const { data: roster, isLoading } = useQuery({ queryKey: ['teacher-roster', user?.id], queryFn: async () => { const { data, error: err } = await supabase.from('teacher_student_links').select('id, student_id, assigned_at, children(id, name, grade_level, username)').order('assigned_at', { ascending: false }); if (err) throw err; return data as unknown as RosterRow[]; }, enabled: Boolean(user) });
  const rosterIds = (roster ?? []).map((row) => row.student_id);
  const { data: progress } = useQuery({ queryKey: ['teacher-students-progress', rosterIds], queryFn: async () => { if (!rosterIds.length) return []; const { data, error: err } = await supabase.from('child_progress').select('child_id, level, accuracy_sum, total_attempts, activities_completed, streak').in('child_id', rosterIds); if (err) throw err; return data as StudentProgress[]; }, enabled: rosterIds.length > 0 });
  const { data: selectedSessions } = useQuery({ queryKey: ['teacher-student-detail-sessions', selectedStudentId], queryFn: async () => { const { data, error: err } = await supabase.from('pronunciation_practice_sessions').select('word, accuracy_percentage, is_correct, created_at').eq('student_id', selectedStudentId!).order('created_at', { ascending: false }).limit(5); if (err) throw err; return data as StudentSession[]; }, enabled: Boolean(selectedStudentId) });
  const { data: selectedAssignments } = useQuery({ queryKey: ['teacher-student-detail-assignments', selectedStudentId], queryFn: async () => { const { data, error: err } = await supabase.from('pdf_assignments').select('id, status, due_date, pdf_materials(title)').eq('student_id', selectedStudentId!).order('assigned_at', { ascending: false }).limit(6); if (err) throw err; return data as unknown as StudentAssignment[]; }, enabled: Boolean(selectedStudentId) });
  const { data: selectedModuleData, isLoading: isLoadingModules, isError: hasModuleError } = useQuery({ queryKey: ['teacher-student-detail-modules', selectedStudentId], queryFn: () => api<{ modules: StudentModule[] }>(`/teacher/students/${selectedStudentId}/modules`, { auth: true }), enabled: Boolean(selectedStudentId) });
  const progressFor = (id: string) => progress?.find((item) => item.child_id === id);
  const rosterForFilter = (roster ?? []).filter((row) => {
    const matchesGrade = gradeFilter === 'all' || String(row.children?.grade_level) === gradeFilter;
    const searchTerm = rosterSearch.trim().toLocaleLowerCase();
    const matchesSearch = !searchTerm || row.children?.name.toLocaleLowerCase().includes(searchTerm) || row.children?.username.toLocaleLowerCase().includes(searchTerm);
    return matchesGrade && matchesSearch;
  });
  const totalRosterPages = Math.max(1, Math.ceil(rosterForFilter.length / ROSTER_PAGE_SIZE));
  const currentRosterPage = Math.min(rosterPage, totalRosterPages);
  const filteredRoster = rosterForFilter.slice((currentRosterPage - 1) * ROSTER_PAGE_SIZE, currentRosterPage * ROSTER_PAGE_SIZE);
  const selectedRow = (roster ?? []).find((row) => row.student_id === selectedStudentId);
  const selectedProgress = selectedStudentId ? progressFor(selectedStudentId) : undefined;
  const selectedAccuracy = selectedProgress?.total_attempts ? Math.round(selectedProgress.accuracy_sum / selectedProgress.total_attempts) : null;
  const completedModules = (selectedModuleData?.modules ?? []).filter((module) => module.state === 'completed');

  return (
    <div className="teacher-roster-page flex min-w-0 flex-col gap-6">
      <header className="flex flex-wrap items-center justify-between gap-4 rounded-3xl border p-5 shadow-card sm:p-6" style={cardStyle('--color-brand-lavender', 8, 28)}><div><p className="text-xs font-bold tracking-[0.12em] text-[var(--color-primary)] uppercase">Class roster</p><h1 className="text-2xl font-bold sm:text-3xl">Mga Mag-aaral</h1><p className="text-sm text-[var(--color-text-muted)]">Hanapin, idagdag, at subaybayan ang iyong mga mag-aaral.</p></div><span className="rounded-2xl bg-white/70 px-4 py-2 text-sm font-bold text-[var(--color-primary)]">{roster?.length ?? 0} assigned</span></header>


      <section aria-labelledby="roster-title"><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><h2 id="roster-title" className="text-xl font-bold">Class List</h2><p className="text-sm text-[var(--color-text-muted)]">Piliin ang card para makita ang mas malinaw na overview.</p></div><label className="text-sm font-bold">Baitang<select value={gradeFilter} onChange={(event) => setGradeFilter(event.target.value)} className="ml-2 min-h-10 rounded-xl border border-[var(--color-border)] bg-white/75 px-3 font-normal"><option value="all">Lahat</option>{gradeLevels.map((grade) => <option key={grade} value={grade}>Grade {grade}</option>)}</select></label></div>
        {isLoading && <p className="rounded-2xl bg-white/60 p-5">Naglo-load...</p>}
        {rosterForFilter.length > ROSTER_PAGE_SIZE && <nav aria-label="Pagination ng class list" className="mb-4 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[var(--color-border)] bg-white/55 px-4 py-3"><p className="text-sm font-semibold text-[var(--color-text-muted)]">Ipinapakita {(currentRosterPage - 1) * ROSTER_PAGE_SIZE + 1}–{Math.min(currentRosterPage * ROSTER_PAGE_SIZE, rosterForFilter.length)} ng {rosterForFilter.length} mag-aaral</p><div className="flex items-center gap-2"><button type="button" onClick={() => setRosterPage((page) => Math.max(1, page - 1))} disabled={currentRosterPage === 1} className="min-h-10 rounded-full border bg-white px-4 text-sm font-bold disabled:opacity-40">← Nakaraan</button><span className="text-sm font-bold" aria-current="page">{currentRosterPage} / {totalRosterPages}</span><button type="button" onClick={() => setRosterPage((page) => Math.min(totalRosterPages, page + 1))} disabled={currentRosterPage === totalRosterPages} className="min-h-10 rounded-full border bg-white px-4 text-sm font-bold disabled:opacity-40">Susunod →</button></div></nav>}
        {!isLoading && !filteredRoster.length && <p className="rounded-3xl border border-dashed border-[var(--color-border)] bg-white/45 p-8 text-center text-[var(--color-text-muted)]">Wala pang mag-aaral sa view na ito.</p>}
        <label className="mb-3 block"><span className="sr-only">Hanapin sa class list</span><input type="search" value={rosterSearch} onChange={(event) => { setRosterSearch(event.target.value); setRosterPage(1); }} className="min-h-11 w-full rounded-2xl border border-[var(--color-border)] bg-white/80 px-4 text-sm" placeholder="Hanapin sa class list..." /></label>
        <div className="overflow-x-auto rounded-3xl border bg-white/55 shadow-card">
          <table className="w-full min-w-[760px] border-collapse text-left text-sm">
            <thead className="border-b border-[var(--color-border)] bg-[var(--color-primary-soft)]/55 text-xs tracking-[0.08em] text-[var(--color-text-muted)] uppercase"><tr><th className="px-5 py-4">Pangalan</th><th className="px-4 py-4">Baitang</th><th className="px-4 py-4">Antas ng pagbasa</th><th className="px-5 py-4">Kahirapan sa pagbasa</th></tr></thead>
            <tbody>{filteredRoster.map((row) => { const student = row.children; const item = progressFor(row.student_id); const accuracy = item?.total_attempts ? Math.round(item.accuracy_sum / item.total_attempts) : null; const difficulty = accuracy === null ? 'Wala pang data' : accuracy < 70 ? 'Kailangan ng tulong' : accuracy < 85 ? 'Katamtaman' : 'Mababa'; const difficultyClass = accuracy === null || accuracy >= 85 ? 'bg-[var(--color-success-soft)] text-[var(--color-success)]' : accuracy < 70 ? 'bg-[var(--color-danger-soft)] text-[var(--color-danger)]' : 'bg-[var(--color-warning-soft)] text-[var(--color-warning-text)]'; return <tr key={row.id} onClick={() => setSelectedStudentId(row.student_id)} className="cursor-pointer border-b border-[var(--color-border)]/70 last:border-0 hover:bg-[var(--color-primary-soft)]/35 focus-within:bg-[var(--color-primary-soft)]/35"><td className="px-5 py-4"><span className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[var(--color-primary-soft)] font-bold text-[var(--color-primary)]">{student?.name.charAt(0) ?? '?'}</span><span><span className="block font-bold">{student?.name ?? 'Hindi kilala'}</span><span className="text-xs text-[var(--color-text-muted)]">{student?.username ?? '—'}</span></span></span></td><td className="px-4 py-4">Grade {student?.grade_level ?? '—'}</td><td className="px-4 py-4">{item?.level ?? 'Walang antas'}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${difficultyClass}`}>{difficulty}</span></td></tr>; })}</tbody>
          </table>
        </div>
        {selectedStudentId && <div className="mt-5 rounded-3xl border p-5 shadow-card sm:p-6" style={cardStyle('--color-brand-teal', 7, 26)}><h3 className="text-lg font-bold">Recent Pronunciation History</h3>{selectedSessions?.length ? <ul className="mt-3 grid grid-cols-1 gap-2 sm:grid-cols-2">{selectedSessions.map((session, index) => <li key={`${session.created_at}-${index}`} className="flex items-center gap-3 rounded-2xl bg-white/65 p-3"><span className={`flex h-9 w-9 items-center justify-center rounded-xl font-bold ${session.is_correct ? 'bg-[var(--color-success-soft)] text-[var(--color-success)]' : 'bg-[var(--color-warning-soft)] text-[var(--color-warning-text)]'}`}>{session.is_correct ? '✓' : '↻'}</span><div className="min-w-0 flex-1"><p className="truncate font-bold">{session.word}</p><time dateTime={session.created_at} className="text-xs text-[var(--color-text-muted)]">{new Date(session.created_at).toLocaleDateString('fil-PH', { month: 'short', day: 'numeric' })}</time></div><span className="font-bold">{session.accuracy_percentage}%</span></li>)}</ul> : <p className="mt-3 text-sm text-[var(--color-text-muted)]">Wala pang recent pronunciation activity.</p>}</div>}
      {selectedStudentId && selectedRow?.children && <section aria-labelledby="student-detail-title" className="rounded-3xl border p-5 shadow-card sm:p-6" style={cardStyle('--color-brand-teal', 7, 26)}>
        <div className="flex flex-wrap items-start justify-between gap-4"><div className="flex min-w-0 items-center gap-3"><span className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-white/75 text-xl font-bold text-[var(--color-primary)]">{selectedRow.children.name.charAt(0)}</span><div className="min-w-0"><p className="text-xs font-bold tracking-[0.1em] text-[var(--color-brand-teal)] uppercase">Detalye ng mag-aaral</p><h3 id="student-detail-title" className="truncate text-xl font-bold">{selectedRow.children.name}</h3><p className="text-sm text-[var(--color-text-muted)]">Grade {selectedRow.children.grade_level} · {selectedProgress?.level ?? 'Wala pang antas na naitala'}</p></div></div><div className="flex flex-wrap gap-2"><Link to="/teacher/progress-reports" className="inline-flex min-h-11 items-center rounded-full bg-white/70 px-4 text-sm font-bold text-[var(--color-primary)] hover:bg-white">Tingnan ang ulat</Link><Link to="/teacher/lessons?tab=pdf" className="inline-flex min-h-11 items-center rounded-full bg-[var(--color-primary)] px-4 text-sm font-bold text-white">Mag-assign ng PDF</Link></div></div>
        <section aria-label="Pagganap sa pagbasa" className="mt-5 grid grid-cols-1 gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-white/65 p-4"><p className="text-xs font-bold text-[var(--color-text-muted)]">Accuracy</p><p className="mt-1 text-2xl font-bold">{selectedAccuracy === null ? '—' : `${selectedAccuracy}%`}</p><p className="text-xs text-[var(--color-text-muted)]">{selectedProgress?.total_attempts ?? 0} pronunciation attempts</p></div><div className="rounded-2xl bg-white/65 p-4"><p className="text-xs font-bold text-[var(--color-text-muted)]">Activities</p><p className="mt-1 text-2xl font-bold">{selectedProgress?.activities_completed ?? 0}</p><p className="text-xs text-[var(--color-text-muted)]">Mga natapos na gawain</p></div><div className="rounded-2xl bg-white/65 p-4"><p className="text-xs font-bold text-[var(--color-text-muted)]">Streak</p><p className="mt-1 text-2xl font-bold">{selectedProgress?.streak ?? 0}</p><p className="text-xs text-[var(--color-text-muted)]">Magkakasunod na araw</p></div></section>
        <div className="mt-5 grid grid-cols-1 gap-4 lg:grid-cols-2"><div><h4 className="font-bold">Kamakailang practice</h4>{selectedSessions?.length ? <ul className="mt-2 flex flex-col gap-2">{selectedSessions.map((session, index) => <li key={`${session.created_at}-${index}`} className="flex items-center justify-between gap-3 rounded-2xl bg-white/65 p-3"><span className="min-w-0"><span className="block truncate font-bold">{session.word}</span><time dateTime={session.created_at} className="text-xs text-[var(--color-text-muted)]">{new Date(session.created_at).toLocaleDateString('fil-PH', { month: 'short', day: 'numeric' })}</time></span><span className="shrink-0 text-sm font-bold">{session.accuracy_percentage}%</span></li>)}</ul> : <p className="mt-2 rounded-2xl bg-white/55 p-3 text-sm text-[var(--color-text-muted)]">Wala pang naitalang practice.</p>}</div><div><h4 className="font-bold">Mga PDF assignment</h4>{selectedAssignments?.length ? <ul className="mt-2 flex flex-col gap-2">{selectedAssignments.map((assignment) => <li key={assignment.id} className="rounded-2xl bg-white/65 p-3"><p className="font-bold">{assignment.pdf_materials?.title ?? 'Materyal sa PDF'}</p><p className="text-xs text-[var(--color-text-muted)]">{assignment.status === 'completed' ? 'Tapos na' : assignment.status === 'in_progress' ? 'Ginagawa' : 'Naka-assign'}{assignment.due_date ? ` · Takdang araw: ${new Date(assignment.due_date).toLocaleDateString('fil-PH', { month: 'short', day: 'numeric' })}` : ''}</p></li>)}</ul> : <p className="mt-2 rounded-2xl bg-white/55 p-3 text-sm text-[var(--color-text-muted)]">Wala pang PDF assignment para sa mag-aaral na ito.</p>}</div></div>
        <section aria-labelledby="completed-modules-title" className="mt-5 rounded-2xl bg-white/50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h4 id="completed-modules-title" className="font-bold">Mga natapos na modyul</h4><p className="text-xs text-[var(--color-text-muted)]">Batay sa recorded module progress ng mag-aaral.</p></div><span className="rounded-full bg-white/70 px-3 py-1 text-sm font-bold text-[var(--color-success)]">{completedModules.length} tapos</span></div>{isLoadingModules ? <p className="mt-3 text-sm text-[var(--color-text-muted)]">Kinukuha ang module progress...</p> : hasModuleError ? <p role="alert" className="mt-3 rounded-xl bg-[var(--color-danger-soft)] p-3 text-sm text-[var(--color-danger)]">Hindi ma-load ang module progress ngayon.</p> : completedModules.length ? <ul className="mt-3 grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3">{completedModules.map((module) => <li key={module.id} className="rounded-2xl bg-white/70 p-3"><p className="font-bold">Modyul {module.module_number}: {module.title}</p><p className="mt-1 text-xs text-[var(--color-text-muted)]">{module.completed_content_item_count}/{module.content_item_count} gawain · Tapos na</p></li>)}</ul> : <p className="mt-3 rounded-xl bg-white/65 p-3 text-sm text-[var(--color-text-muted)]">Wala pang natapos na modyul na naitala.</p>}</section>
      <button type="button" onClick={() => setSelectedStudentId(null)} className="absolute top-4 right-4 flex h-10 w-10 items-center justify-center rounded-full border bg-white text-xl font-bold text-[var(--color-text)] shadow-card hover:bg-[var(--color-primary-soft)]" aria-label="Isara ang detalye ng mag-aaral">×</button></section>}
      <style>{`
        .teacher-roster-page section[aria-labelledby='student-detail-title'] {
          position: fixed;
          z-index: 60;
          top: 50%;
          left: 50%;
          width: min(56rem, calc(100vw - 2rem));
          max-height: calc(100vh - 2rem);
          transform: translate(-50%, -50%);
          overflow-y: auto;
          background: var(--color-surface);
          box-shadow: 0 0 0 100vmax rgb(15 23 42 / 55%), var(--shadow-raised);
        }
        .teacher-roster-page section[aria-labelledby='student-detail-title'] > div:first-child {
          padding-right: 3.5rem;
        }
      `}</style>
      </section>
    </div>
  );
}
