-- Completes Filipino-only meanings for active word-level reading content.
-- These are concise, child-friendly vocabulary aids shown by the student UI.
INSERT INTO public.word_definitions (word_key, meaning_fil, is_ambiguous) VALUES
  ('aparador', 'Malaking kabinet na lagayan ng damit o ibang gamit.', false),
  ('asin', 'Puting pampalasa na inilalagay sa pagkain.', false),
  ('balat', 'Panlabas na takip ng katawan, prutas, o halaman.', false),
  ('balikat', 'Bahagi ng katawan sa pagitan ng leeg at braso.', false),
  ('balon', 'Malalim na hukay na pinagkukunan ng tubig.', false),
  ('bayabas', 'Prutas na bilog o pahaba at maraming maliliit na buto.', false),
  ('bestida', 'Damit na karaniwang isang piraso para sa babae.', false),
  ('bigas', 'Butil ng palay na niluluto upang maging kanin.', false),
  ('bilugan', 'Gawing bilog ang hugis.', false),
  ('binili', 'Nakuha kapalit ng bayad.', false),
  ('bintana', 'Butas o bahagi ng bahay na pinapasukan ng hangin at liwanag.', false),
  ('binuksan', 'Ginawang bukas ang isang bagay.', false),
  ('bubong', 'Pinakatakip sa itaas ng bahay.', false),
  ('bubuyog', 'Maliit na insektong kumukuha ng nektar sa bulaklak.', false),
  ('buhok', 'Mga hiblang tumutubo sa ulo o katawan.', false),
  ('bulaklak', 'Bahagi ng halaman na kadalasang makulay at mabango.', false),
  ('bumaba', 'Pumunta mula sa mataas tungo sa mas mababang lugar.', false),
  ('bumalik', 'Pumunta muli sa dating lugar o gawain.', false),
  ('bumasa', 'Nagbasa o tumingin sa mga salitang nakasulat.', false),
  ('dalawa', 'Bilang na kasunod ng isa.', false),
  ('delikado', 'May panganib at kailangang pag-ingatan.', false),
  ('dinala', 'Isinama o inihatid sa ibang lugar.', false),
  ('dingding', 'Patayong bahagi ng bahay na naghahati o nakapaligid sa silid.', false),
  ('edukasyon', 'Pag-aaral na nagbibigay ng kaalaman at kasanayan.', false),
  ('gamot', 'Bagay na ginagamit upang gumaling ang may sakit.', false),
  ('gumalaw', 'Kumilos o nagbago ng puwesto.', false),
  ('gumuguhit', 'Lumilikha ng larawan gamit ang lapis, krayola, o iba pa.', false),
  ('hagdanan', 'Mga baitang na daanan paakyat o pababa.', false),
  ('halaman', 'Nabubuhay na bagay na tumutubo sa lupa at may dahon.', false),
  ('hinanap', 'Sinikap makita o matagpuan.', false),
  ('hinati', 'Pinaghiwalay sa dalawa o higit pang bahagi.', false),
  ('hinugasan', 'Nilinis gamit ang tubig.', false),
  ('humiga', 'Inilapag ang katawan upang magpahinga o matulog.', false),
  ('ilaw', 'Bagay na nagbibigay-liwanag.', false),
  ('imahinasyon', 'Kakayahang bumuo ng larawan o ideya sa isip.', false),
  ('impormasyon', 'Kaalaman o balitang nalalaman tungkol sa isang bagay.', false),
  ('inayos', 'Ginawang maayos at nasa tamang lugar.', false),
  ('ipis', 'Maliit na insektong karaniwang nakikita sa bahay.', false),
  ('isinara', 'Ginawang hindi bukas.', false),
  ('kahoy', 'Matigas na bahagi ng puno na ginagamit din sa paggawa ng gamit.', false),
  ('kaliwa', 'Direksiyong kabaligtaran ng kanan.', false),
  ('kamiseta', 'Damit na isinusuot sa itaas na bahagi ng katawan.', false),
  ('kamote', 'Ugat na gulay na maaaring dilaw, kahel, o lila ang laman.', false),
  ('kape', 'Inuming gawa sa butil ng kape.', false),
  ('kilay', 'Buhok na nasa itaas ng mata.', false),
  ('kisame', 'Pinakatakip sa loob na bahagi ng silid.', false),
  ('komunikasyon', 'Pagpapalitan ng mensahe o impormasyon.', false),
  ('kooperasyon', 'Pagtutulungan upang matapos ang isang gawain.', false),
  ('kumanta', 'Umawit o bumigkas ng awit.', false),
  ('kumuha', 'Tumanggap o pumili ng isang bagay.', false),
  ('kurtina', 'Telang nakasabit na pantakip sa bintana.', false),
  ('kutsara', 'Kagamitang ginagamit sa pagsalok o pagkain.', false),
  ('lalagyan', 'Bagay na ginagamit upang maglagay o mag-imbak ng iba pang bagay.', false),
  ('lamesa', 'Patag na muwebles na ginagamit sa pagkain, pagsulat, o pagtatrabaho.', false),
  ('langaw', 'Maliit na insektong may pakpak.', false),
  ('laruan', 'Bagay na ginagamit ng bata sa paglalaro.', false),
  ('lata', 'Sisidlang yari sa manipis na metal.', false),
  ('ligtas', 'Walang panganib o kapahamakan.', false),
  ('likod', 'Bahagi ng katawan sa likuran ng dibdib.', false),
  ('limang', 'Bilang na lima kapag may kasunod na pangngalan.', false),
  ('literatura', 'Mga akdang binabasa tulad ng kuwento, tula, at dula.', false),
  ('lubid', 'Mahabang tali na gawa sa pinagtitirintas na hibla.', false),
  ('lumabas', 'Umalis mula sa loob tungo sa labas.', false),
  ('lumakad', 'Gumalaw gamit ang mga paa.', false),
  ('lumangoy', 'Gumalaw sa tubig gamit ang mga braso at paa.', false),
  ('luya', 'Ugat na pampalasa at halamang gamot.', false),
  ('maanghang', 'May matapang na lasa na nagpapainit sa dila.', false),
  ('maayos', 'Malinis, nasa tamang lugar, o mahusay ang pagkakagawa.', false),
  ('mababa', 'Hindi mataas ang kinalalagyan o sukat.', false),
  ('mabagal', 'Hindi mabilis kumilos o mangyari.', false),
  ('mabaho', 'May amoy na hindi kaaya-aya.', false),
  ('mabango', 'May amoy na kaaya-aya.', false),
  ('madilim', 'Kaunti o walang liwanag.', false),
  ('magaspang', 'Hindi makinis sa haplos.', false),
  ('magdilig', 'Magbuhos ng tubig sa halaman.', false),
  ('maghugas', 'Maglinis gamit ang tubig.', false),
  ('magkano', 'Tanong tungkol sa halaga o presyo.', false),
  ('magkulay', 'Lagyan ng kulay ang larawan o bagay.', false),
  ('maglaro', 'Gumawa ng masayang gawain para aliwin ang sarili.', false),
  ('maglinis', 'Alisin ang dumi at ayusin ang lugar o bagay.', false),
  ('magluto', 'Maghanda ng pagkain gamit ang init o apoy.', false),
  ('magtanim', 'Maglagay ng buto o punla sa lupa upang tumubo.', false),
  ('magulo', 'Hindi maayos ang ayos o mahirap unawain.', false),
  ('magwalis', 'Maglinis ng sahig gamit ang walis.', false),
  ('mahaba', 'Malaki ang sukat mula dulo hanggang dulo.', false),
  ('mahina', 'Kaunti ang lakas o tunog.', false),
  ('mahinhin', 'Kalmado at maayos kumilos o magsalita.', false),
  ('maikli', 'Hindi mahaba.', false),
  ('mais', 'Halaman na may butil na maaaring kainin o gawing pagkain.', false),
  ('makapal', 'Malaki ang sukat mula ibabaw hanggang ilalim.', false),
  ('makinis', 'Pantay at malambot sa haplos.', false),
  ('makulay', 'May marami o matingkad na kulay.', false),
  ('malakas', 'May maraming lakas o matinding tunog.', false),
  ('malaki', 'Malawak o mataas ang sukat.', false),
  ('malambot', 'Madaling madiin o hindi matigas.', false),
  ('mali', 'Hindi wasto o hindi tama.', false),
  ('maliit', 'Hindi malaki ang sukat.', false),
  ('malinis', 'Walang dumi.', false),
  ('malungkot', 'May damdaming lungkot o hindi masaya.', false),
  ('maluwag', 'May sapat na espasyo at hindi masikip.', false),
  ('mani', 'Maliit na butil na kinakain at tumutubo sa lupa.', false),
  ('manipis', 'Kaunti ang sukat mula ibabaw hanggang ilalim.', false),
  ('mapa', 'Larawang nagpapakita ng lugar at direksiyon.', false),
  ('mapait', 'Lasang tulad ng ampalaya o gamot.', false),
  ('maputi', 'Kulay na tulad ng ulap o papel.', false),
  ('marumi', 'May dumi at kailangang linisin.', false),
  ('masarap', 'May kaaya-ayang lasa.', false),
  ('masaya', 'May damdaming tuwa.', false),
  ('masikip', 'Maliit ang espasyo at hirap gumalaw.', false),
  ('mataas', 'Malaki ang layo mula sa ibaba patungo sa itaas.', false),
  ('matigas', 'Hindi madaling madiin o mabali.', false),
  ('maya', 'Maliit na ibon na karaniwang nakikita malapit sa bahay.', false),
  ('medyas', 'Damit na isinusuot sa paa bago magsapatos.', false),
  ('melon', 'Malaking prutas na may matamis at makatas na laman.', false),
  ('na', 'Salitang nag-uugnay o nagpapakita na tapos na ang isang kilos.', false),
  ('nagbigay', 'Nag-abot o naghandog ng isang bagay.', false),
  ('nagdala', 'Nagbitbit o nagsama ng isang bagay.', false),
  ('naghintay', 'Nanatili hanggang dumating ang inaasahan.', false),
  ('naglakbay', 'Pumunta sa malayong lugar.', false),
  ('nagtanong', 'Humingi ng sagot o impormasyon.', false),
  ('nakikinig', 'Pinagtutuunan ng pansin ang tunog o nagsasalita.', false),
  ('nakita', 'Natanaw o napansin gamit ang mata.', false),
  ('naliligo', 'Naghuhugas ng katawan gamit ang tubig.', false),
  ('namimili', 'Pumipili o bumibili ng kailangan.', false),
  ('narinig', 'Napakinggan o naunawaan gamit ang tainga.', false),
  ('natutulog', 'Nagpapahinga habang nakapikit.', false),
  ('nilinis', 'Inalisan ng dumi.', false),
  ('niluto', 'Inihanda sa init upang maging pagkain.', false),
  ('ngipin', 'Matigas na bahagi sa bibig na ginagamit sa pagnguya.', false),
  ('oras', 'Sukat ng panahon; ginagamit din sa pagsasabi ng panahon sa relo.', false),
  ('organisasyon', 'Pangkat ng mga taong nagtutulungan para sa iisang layunin.', false),
  ('pader', 'Patayong bahagi ng bahay na nakapaligid o naghahati sa silid.', false),
  ('palay', 'Halaman na pinagmumulan ng bigas.', false),
  ('papaya', 'Prutas na may kahel o dilaw na laman at maraming buto.', false),
  ('parisukat', 'Hugis na may apat na magkakapantay na gilid.', false),
  ('pera', 'Salaping ginagamit sa pagbili at pagbabayad.', false),
  ('peras', 'Prutas na karaniwang bilog sa ibaba at makitid sa itaas.', false),
  ('pinili', 'Kinuha mula sa maraming pagpipilian.', false),
  ('pintuan', 'Bahagi ng bahay na binubuksan at isinasara para makadaan.', false),
  ('pitong', 'Bilang na pito kapag may kasunod na pangngalan.', false),
  ('plato', 'Patag na sisidlan na ginagamit sa pagkain.', false),
  ('preparasyon', 'Paghahanda bago gawin ang isang bagay.', false),
  ('presentasyon', 'Pagpapakita o pagpapaliwanag ng isang paksa sa harap ng iba.', false),
  ('pumasok', 'Pumunta mula sa labas tungo sa loob.', false),
  ('puno', 'Púno = malaking halaman na may katawan, sanga, at dahon; punô = wala nang bakanteng espasyo.', true),
  ('pusit', 'Hayop-dagat na may malalambot na galamay.', false),
  ('puso', 'Bahagi ng katawan na nagpapadaloy ng dugo; maaari ring tumukoy sa damdamin.', false),
  ('putik', 'Basang lupa na malambot at malagkit.', false),
  ('responsibilidad', 'Tungkuling dapat gawin nang maayos.', false),
  ('sabado', 'Ikapitong araw ng linggo bago ang Linggo.', false),
  ('sabon', 'Bagay na ginagamit sa paghuhugas at paglilinis.', false),
  ('sahig', 'Patag na bahaging inaapakan sa loob ng bahay.', false),
  ('salamin', 'Bagay na nagpapakita ng repleksiyon; maaari ring gamit sa bintana.', false),
  ('sapatos', 'Pangtakip at proteksiyon sa paa.', false),
  ('sariwa', 'Bago, malinis, at hindi pa luma o panis.', false),
  ('siko', 'Bahagi ng braso na nagdurugtong sa itaas at ibabang braso.', false),
  ('silungan', 'Lugar na pansamantalang proteksiyon laban sa araw o ulan.', false),
  ('sinabi', 'Ipinahayag sa pamamagitan ng pagsasalita.', false),
  ('sipon', 'Likido sa ilong kapag may sakit o allergy.', false),
  ('sitaw', 'Mahabang berdeng gulay na may buto sa loob.', false),
  ('suka', 'Maasim na likido na ginagamit na pampalasa.', false),
  ('sumagot', 'Nagbigay ng tugon sa tanong o sinabi.', false),
  ('sumakay', 'Umakyat sa sasakyan o hayop upang maglakbay.', false),
  ('sumayaw', 'Gumalaw ayon sa tugtog o musika.', false),
  ('sumulat', 'Gumawa ng mga letra o salita gamit ang panulat.', false),
  ('susi', 'Kagamitang pambukas at pansara ng kandado.', false),
  ('tahimik', 'Walang maingay na tunog o kalmado.', false),
  ('tasa', 'Maliit na sisidlan na iniinuman ng mainit o malamig na inumin.', false),
  ('teknolohiya', 'Paggamit ng kaalaman at mga kagamitan upang mapadali ang gawain.', false),
  ('tinawag', 'Binanggit ang pangalan o inanyayahan.', false),
  ('tinupi', 'Pinagpatong ang bahagi ng papel o tela.', false),
  ('tiyan', 'Bahagi ng katawan sa ilalim ng dibdib na kinalalagyan ng sikmura.', false),
  ('toyo', 'Maalat na sawsawang gawa sa toyo o soybean.', false),
  ('tubo', 'Halaman na may matamis na katas; maaari ring tumukoy sa kinita.', true),
  ('tumalon', 'Umalis sa lupa gamit ang biglang lakas ng mga paa.', false),
  ('tumawag', 'Nagsalita upang kunin ang pansin ng iba o gumamit ng telepono.', false),
  ('tumayo', 'Umalis sa pagkakaupo o paghiga at naging nakatindig.', false),
  ('ubas', 'Maliit na prutas na karaniwang tumutubo nang kumpol.', false),
  ('ulam', 'Pagkaing isinasabay sa kanin.', false),
  ('umakyat', 'Pumunta sa mas mataas na lugar.', false),
  ('umupo', 'Lumagay sa posisyong nakapatong ang katawan sa upuan o ibang patungan.', false),
  ('walis', 'Kagamitang pantanggal ng dumi sa sahig.', false),
  ('yelo', 'Tubig na nagyelo at naging matigas.', false)
ON CONFLICT (word_key) DO UPDATE
SET meaning_fil = EXCLUDED.meaning_fil,
    is_ambiguous = EXCLUDED.is_ambiguous,
    updated_at = now();

NOTIFY pgrst, 'reload schema';
