import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { ArrowRight, Award, BookOpen, BookOpenCheck, CalendarDays, Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, FileText, Lightbulb, PlayCircle, Sparkles, Target, Trophy, UsersRound } from 'lucide-react';
import { supabase } from '../../lib/supabaseClient';
import { useAuth } from '../../lib/auth/AuthContext';
import { api } from '../../lib/api';
import type { ReadingProfile } from '../../components/ReadingInsightsPanel';
import heroArt from '../../assets/parent/hero.png';
import currentModuleArt from '../../assets/parent/current.png';
import readingBadge from '../../assets/parent/reading.png';
import streakBadge from '../../assets/parent/streak.png';
import championBadge from '../../assets/parent/reading_champion.png';
import noEnrolledChildArt from '../../assets/parent/no enrolled child.png';
import noActivitiesArt from '../../assets/parent/no activities.png';

interface Child { id: string; name: string; grade_level: number; }
interface ChildProgress { child_id: string; level: string; word_count: number; streak: number; }
interface PracticeSession { word: string; accuracy_percentage: number; is_correct: boolean; duration_seconds: number | null; created_at: string; }
const moduleNames = ['Unang mga Titik', 'Hanay ng Ba', 'Hanay ng Da', 'Hanay ng Ga', 'Hanay ng Ha'];

function formatRelativeDate(iso: string) {
  const hours = Math.floor((Date.now() - new Date(iso).getTime()) / 3_600_000);
  if (hours < 1) return 'Kamakailan lang';
  if (hours < 24) return `${hours} oras ang nakalipas`;
  return new Date(iso).toLocaleDateString('fil-PH', { month: 'short', day: 'numeric' });
}
function IconBubble({ children, color = 'blue' }: { children: React.ReactNode; color?: 'blue' | 'green' | 'gold' | 'violet' | 'rose' }) { return <span className={`parent-icon-bubble parent-icon-${color}`}>{children}</span>; }

export default function Dashboard() {
  const { user, identity } = useAuth();
  const [selectedChildId, setSelectedChildId] = useState<string | null>(null);
  const [calendarMonth, setCalendarMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1));
  const { data: children } = useQuery({ queryKey: ['parent-children', user?.id], queryFn: async () => { const { data, error } = await supabase.from('children').select('id, name, grade_level').order('name'); if (error) throw error; return data as Child[]; }, enabled: Boolean(user) });
  const activeChildId = selectedChildId ?? children?.[0]?.id ?? null;
  const activeChild = children?.find((child) => child.id === activeChildId) ?? null;
  const { data: progress } = useQuery({ queryKey: ['parent-child-progress', activeChildId], queryFn: async () => { const { data, error } = await supabase.from('child_progress').select('child_id, level, word_count, streak').eq('child_id', activeChildId!).maybeSingle(); if (error) throw error; return data as ChildProgress | null; }, enabled: Boolean(activeChildId) });
  const { data: sessions } = useQuery({ queryKey: ['parent-child-sessions', activeChildId], queryFn: async () => { const { data, error } = await supabase.from('pronunciation_practice_sessions').select('word, accuracy_percentage, is_correct, duration_seconds, created_at').eq('student_id', activeChildId!).order('created_at', { ascending: false }).limit(50); if (error) throw error; return data as PracticeSession[]; }, enabled: Boolean(activeChildId) });
  const { data: readingProfile } = useQuery({ queryKey: ['parent-reading-profile', activeChildId], queryFn: () => api<{ profile: ReadingProfile }>(`/parent/children/${activeChildId}/reading-profile`, { auth: true }), enabled: Boolean(activeChildId) });
  const { data: upcoming } = useQuery({ queryKey: ['parent-upcoming', activeChildId], queryFn: async () => { const { data, error } = await supabase.from('scheduled_activities').select('id, title, scheduled_date').eq('child_id', activeChildId!).eq('status', 'scheduled').order('scheduled_date', { ascending: true }).limit(3); if (error) throw error; return data as { id: string; title: string; scheduled_date: string }[]; }, enabled: Boolean(activeChildId) });
  const profile = readingProfile?.profile;
  const averageAccuracy = profile?.averageAccuracy ?? 0;
  const completed = profile?.completedContentCount ?? 0;
  const totalModules = 17;
  const progressPercent = Math.min(100, Math.round((completed / totalModules) * 100));
  const currentModuleIndex = Math.min(moduleNames.length - 1, Math.floor(completed / 3));
  const currentModule = moduleNames[currentModuleIndex];
  const parentFirstName = identity?.displayName?.split(' ')[0] ?? 'Magulang';
  const displayName = activeChild?.name ?? 'Iyong Anak';
  const today = new Date();
  const monthStartDay = calendarMonth.getDay();
  const daysInCalendarMonth = new Date(calendarMonth.getFullYear(), calendarMonth.getMonth() + 1, 0).getDate();
  const calendarDays = Array.from({ length: Math.ceil((monthStartDay + daysInCalendarMonth) / 7) * 7 }, (_, index) => index - monthStartDay + 1);
  const scheduledDays = new Set((upcoming ?? []).filter((item) => { const date = new Date(item.scheduled_date); return date.getFullYear() === calendarMonth.getFullYear() && date.getMonth() === calendarMonth.getMonth(); }).map((item) => new Date(item.scheduled_date).getDate()));
  if (children && children.length === 0) return <div className="parent-empty-state"><img src={noEnrolledChildArt} alt="" className="parent-empty-art" /><h1>Magsimula sa pag-enroll ng anak</h1><p>Idagdag ang account ng iyong anak upang makita ang kaniyang progreso at mga gawain.</p><Link to="/parent/children">I-enroll ang Unang Anak <ArrowRight size={17} /></Link></div>;
  return <div className="parent-reference-dashboard">
    <header className="parent-reference-hero"><div className="parent-hero-copy"><h1><span className="parent-header-family-icon" aria-hidden="true"><UsersRound size={25} /></span>Magandang araw, {parentFirstName}! <span>☀️</span></h1><p>Suportahan natin ang pagkatuto ni {displayName}.<br />Narito ang kanyang kasalukuyang progreso.</p></div><div className="parent-hero-quote"><Sparkles size={22} /><p>Bawat maliit na hakbang ay malaking pag-unlad.</p></div><img src={heroArt} alt="" aria-hidden="true" className="parent-hero-art" /></header>
    <section className="parent-child-switcher" aria-label="Piliin ang anak"><div><p>Piliin ang Anak</p><label className="parent-child-select"><span className="parent-child-initial">{displayName.charAt(0).toUpperCase()}</span><span><strong>{displayName}</strong><small>Grade {activeChild?.grade_level ?? '—'} • {progress?.level ?? 'Beginner'} Level</small></span><ChevronDown size={18} /><select aria-label="Piliin ang anak" value={activeChildId ?? ''} onChange={(event) => setSelectedChildId(event.target.value)}>{children?.map((child) => <option key={child.id} value={child.id}>{child.name}</option>)}</select></label></div><Link to="/parent/children" className="parent-add-child">＋ Magdagdag ng Anak</Link></section>
    <div className="parent-dashboard-grid"><div className="parent-dashboard-column">
      <section className="parent-panel parent-progress-panel"><h2><IconBubble><BookOpen size={20} /></IconBubble>Kabuuang Progreso</h2><div className="parent-progress-body"><div className="parent-donut" style={{ '--progress': `${progressPercent * 3.6}deg` } as React.CSSProperties}><div><strong>{progressPercent}%</strong><small>{completed} / {totalModules}<br />modules</small></div></div><div className="parent-stat-list"><div><IconBubble color="green"><BookOpenCheck size={16} /></IconBubble><p><strong>{completed} / {totalModules}</strong><small>Mga Aktibidad</small></p></div><div><IconBubble color="gold"><Check size={16} /></IconBubble><p><strong>{averageAccuracy}%</strong><small>Average Score</small></p></div><div><IconBubble><Target size={16} /></IconBubble><p><strong>{progress?.level ?? 'Beginner'} Level</strong><small>Kasalukuyang Level</small></p></div><div><IconBubble color="violet"><Award size={16} /></IconBubble><p><strong>{currentModule}</strong><small>Kasalukuyang Modyul</small></p></div></div></div></section>
      <section className="parent-panel parent-current-module"><div className="parent-panel-head"><h2><IconBubble><BookOpen size={20} /></IconBubble>Kasalukuyang Modyul</h2><Link to="/parent/progress?tab=modules">Magpatuloy <ArrowRight size={16} /></Link></div><div className="parent-module-main"><div className="parent-module-illustration"><img src={currentModuleArt} alt="" /></div><div><h3>{currentModule}</h3><p>Modyul {currentModuleIndex + 1} • {completed} / {totalModules} aktibidad</p><div className="parent-inline-progress"><i style={{ width: `${progressPercent}%` }} /></div><strong>{progressPercent}%</strong></div></div><p className="parent-module-note">Patuloy na sanayin ang pagbasa at pagkilala ng mga tunog.</p></section>
      <section className="parent-panel parent-module-list"><div className="parent-panel-head"><h2><IconBubble><BookOpen size={20} /></IconBubble>Progreso sa Bawat Modyul</h2><Link to="/parent/progress?tab=modules">Tingnan Lahat <ArrowRight size={15} /></Link></div><ol>{moduleNames.map((name, index) => { const isCurrent = index === currentModuleIndex; const done = index < currentModuleIndex; const value = done ? 100 : isCurrent ? progressPercent : 0; return <li key={name}><Link to="/parent/progress?tab=modules" aria-label={`Tingnan ang progreso ng ${name}`}><span className="parent-module-number">{index + 1}</span><strong>{name}</strong><span className={`parent-module-status ${done ? 'done' : isCurrent ? 'active' : ''}`}>{done ? '✓ Tapos na' : isCurrent ? '◉ Isinasagawa' : 'Hindi Pa Nagsisimula'}</span><div className="parent-row-progress"><i style={{ width: `${value}%` }} /></div><b>{value}%</b><ChevronRight size={18} /></Link></li>; })}</ol></section>
      <section className="parent-panel parent-schedule-panel"><div className="parent-panel-head"><h2><IconBubble><CalendarDays size={20} /></IconBubble>Iskedyul ng Pag-aaral</h2><Link to="/parent/schedule">Buksan ang Kalendaryo <ArrowRight size={15} /></Link></div><div className="parent-schedule-content"><div className="parent-calendar"><div className="parent-calendar-controls"><button type="button" aria-label="Nakaraang buwan" onClick={() => setCalendarMonth((month) => new Date(month.getFullYear(), month.getMonth() - 1, 1))}><ChevronLeft size={16} /></button><strong>{calendarMonth.toLocaleDateString('fil-PH', { month: 'long', year: 'numeric' })}</strong><button type="button" aria-label="Susunod na buwan" onClick={() => setCalendarMonth((month) => new Date(month.getFullYear(), month.getMonth() + 1, 1))}><ChevronRight size={16} /></button></div><div className="parent-calendar-grid">{['Lin', 'Lun', 'Mar', 'Miy', 'Huy', 'Biy', 'Sab'].map((day) => <b key={day}>{day}</b>)}{calendarDays.map((day, index) => day < 1 || day > daysInCalendarMonth ? <span className="calendar-empty" key={`blank-${index}`} /> : <Link to="/parent/schedule" aria-label={`Tingnan ang iskedyul sa ${day} ${calendarMonth.toLocaleDateString('fil-PH', { month: 'long', year: 'numeric' })}`} className={`${day === today.getDate() && calendarMonth.getMonth() === today.getMonth() && calendarMonth.getFullYear() === today.getFullYear() ? 'today' : ''} ${scheduledDays.has(day) ? 'has-schedule' : ''}`} key={day}>{day}</Link>)}</div></div><div className="parent-upcoming-list"><h3>Mga Naka-iskedyul na Gawain</h3>{upcoming?.length ? upcoming.map((item) => <Link to="/parent/schedule" key={item.id}><IconBubble color="violet"><BookOpen size={15} /></IconBubble><p><strong>{item.title}</strong><small>{new Date(item.scheduled_date).toLocaleString('fil-PH', { dateStyle: 'medium', timeStyle: 'short' })}</small></p></Link>) : <p className="parent-muted">Wala pang naka-iskedyul na gawain.</p>}</div></div></section>
    </div><aside className="parent-dashboard-column">
      <section className="parent-panel parent-achievements"><div className="parent-panel-head"><h2><IconBubble color="gold"><Trophy size={20} /></IconBubble>Mga Kamakailang Nakamit</h2><Link to="/parent/progress">Tingnan Lahat <ArrowRight size={15} /></Link></div><div className="parent-badges"><div><img src={readingBadge} alt="" /><strong>Mahusay na Simula</strong></div><div><img src={streakBadge} alt="" /><strong>{progress?.streak ?? 0}-Day Reading Streak</strong></div><div><img src={championBadge} alt="" /><strong>Patuloy na Pagsisikap</strong></div></div><div className="parent-cheer"><span>👏</span><div><strong>Mahusay, {displayName}!</strong><p>Patuloy ang iyong pag-unlad sa pagbabasa.</p></div></div></section>
      <section className="parent-panel parent-quick-actions"><h2><IconBubble><Sparkles size={20} /></IconBubble>Mabilis na Pagkilos</h2><div><Link to="/parent/progress?tab=modules"><BookOpenCheck size={27} /><span>Tingnan ang<br />Buong Progreso</span></Link><Link to="/parent/schedule"><CalendarDays size={27} /><span>Tingnan ang<br />Iskedyul</span></Link><Link to="/parent/progress?tab=activities"><FileText size={27} /><span>Mga Gawain<br />at PDF</span></Link></div><Link to="/parent/progress?tab=modules" className="parent-recommendation"><IconBubble color="gold"><Lightbulb size={21} /></IconBubble><span><strong>Mga Rekomendasyon</strong><small>para kay {displayName}</small></span></Link></section>
      <section className="parent-panel parent-recent"><div className="parent-panel-head"><h2><IconBubble><PlayCircle size={20} /></IconBubble>Kamakailang Aktibidad</h2><Link to="/parent/progress">Tingnan Lahat <ArrowRight size={15} /></Link></div><div className="parent-activity-list">{sessions?.length ? sessions.slice(0, 5).map((session, index) => <div key={`${session.created_at}-${index}`}><IconBubble color={session.is_correct ? 'green' : 'blue'}>{session.is_correct ? <CheckCircle2 size={17} /> : <PlayCircle size={17} />}</IconBubble><p><strong>{session.is_correct ? 'Natapos na ang Practice' : 'Sinimulan ang Practice'}</strong><small>{session.word} • {session.accuracy_percentage}% kawastuhan</small></p><time>{formatRelativeDate(session.created_at)}</time></div>) : <div className="parent-empty-inline"><img src={noActivitiesArt} alt="" /><p className="parent-muted">Wala pang aktibidad.</p></div>}</div></section>
      <section className="parent-panel parent-tips"><h2><IconBubble color="gold"><Lightbulb size={20} /></IconBubble>Mga Rekomendasyon</h2><div><IconBubble><BookOpenCheck size={18} /></IconBubble><p><strong>Magpatuloy sa {currentModule}</strong><small>{profile?.recommendedHomePractice ?? 'Tapusin ang mga natitirang aktibidad.'}</small></p><ChevronRight size={18} /></div><div><IconBubble color="green"><FileText size={18} /></IconBubble><p><strong>Karagdagang Practice</strong><small>Magkaroon ng 10 minuto araw-araw na pagbasa.</small></p><ChevronRight size={18} /></div><div><IconBubble color="gold"><UsersRound size={18} /></IconBubble><p><strong>Review sa Bahay</strong><small>Magbalik sa ilang natapos na gawain para mas tumibay ang pagkatuto.</small></p><ChevronRight size={18} /></div></section>
    </aside></div>
    <section className="parent-panel parent-resources"><div className="parent-panel-head"><div><h2><IconBubble><BookOpen size={20} /></IconBubble>Mga Karagdagang Resources</h2><p>Mga materyal na makakatulong sa pagkatuto ni {displayName} sa bahay.</p></div><Link to="/parent/progress">Tingnan Lahat <ArrowRight size={15} /></Link></div><div className="parent-resource-grid"><Link to="/parent/progress"><IconBubble color="gold"><FileText size={22} /></IconBubble><span><strong>Worksheets</strong><small>I-download ang mga practice worksheets.</small></span></Link><Link to="/parent/progress"><IconBubble color="green"><BookOpen size={22} /></IconBubble><span><strong>Mga Flashcards</strong><small>Para sa mas masayang pag-aaral.</small></span></Link><Link to="/parent/messages"><IconBubble color="gold"><UsersRound size={22} /></IconBubble><span><strong>Gabay sa Magulang</strong><small>Mga tips at strategies.</small></span></Link><Link to="/parent/progress"><IconBubble color="rose"><PlayCircle size={22} /></IconBubble><span><strong>Mga Video</strong><small>Maikling aralin at gabay.</small></span></Link></div></section>
  </div>;
}
