import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link, useSearchParams } from 'react-router-dom';
import { Award, BarChart3, BookOpen, CalendarDays, CheckCircle2, ChevronDown, ChevronRight, Clock3, List, Lock, PlayCircle, Sparkles, Star, Trophy } from 'lucide-react';
import { supabase } from '../../lib/supabaseClient';
import { useAuth } from '../../lib/auth/AuthContext';
import { api } from '../../lib/api';
import type { ReadingProfile } from '../../components/ReadingInsightsPanel';
import { BADGE_CATALOG } from '../../lib/badges';
import currentModuleArt from '../../assets/parent/current.png';
import noActivitiesArt from '../../assets/parent/no activities.png';
import './parent-progress-reference.css';

interface Child { id: string; name: string; grade_level: number; }
interface PracticeSession { created_at: string; accuracy_percentage: number; is_correct: boolean; duration_seconds: number | null; }
interface ChildAchievements { achievements: { id: string; unlockedAt?: string }[] | Record<string, unknown> | null; }
const modules = ['Unang mga Titik', 'Hanay ng Ba', 'Hanay ng Da', 'Hanay ng Ga', 'Hanay ng Ha', 'Hanay ng Ka', 'Hanay ng La', 'Hanay ng Ma'];
type ProgressTab = 'modules' | 'activities' | 'results' | 'time';

export default function ProgressReport() {
  const { user } = useAuth();
  const [searchParams, setSearchParams] = useSearchParams();
  const [selectedChildId, setSelectedChildId] = useState<string | null>(null);
  const requestedTab = searchParams.get('tab');
  const activeTab: ProgressTab = requestedTab === 'activities' || requestedTab === 'results' || requestedTab === 'time' || requestedTab === 'modules' ? requestedTab : 'modules';
  const { data: children } = useQuery({ queryKey: ['parent-children', user?.id], queryFn: async () => { const { data, error } = await supabase.from('children').select('id, name, grade_level').order('name'); if (error) throw error; return data as Child[]; }, enabled: Boolean(user) });
  const activeChildId = selectedChildId ?? children?.[0]?.id ?? null;
  const activeChild = children?.find((child) => child.id === activeChildId);
  const { data: sessions, isLoading } = useQuery({ queryKey: ['child-practice-sessions', activeChildId], queryFn: async () => { const { data, error } = await supabase.from('pronunciation_practice_sessions').select('created_at, accuracy_percentage, is_correct, duration_seconds').eq('student_id', activeChildId!).order('created_at', { ascending: false }).limit(100); if (error) throw error; return data as PracticeSession[]; }, enabled: Boolean(activeChildId) });
  const { data: readingProfile } = useQuery({ queryKey: ['parent-reading-profile', activeChildId], queryFn: () => api<{ profile: ReadingProfile }>(`/parent/children/${activeChildId}/reading-profile`, { auth: true }), enabled: Boolean(activeChildId) });
  const { data: childProgress } = useQuery({ queryKey: ['parent-child-achievements', activeChildId], queryFn: async () => { const { data, error } = await supabase.from('child_progress').select('achievements').eq('child_id', activeChildId!).maybeSingle(); if (error) throw error; return data as ChildAchievements | null; }, enabled: Boolean(activeChildId) });
  const profile = readingProfile?.profile;
  const completed = profile?.completedContentCount ?? 0;
  const totalActivities = 52;
  const progressPercent = Math.min(100, Math.round((completed / totalActivities) * 100));
  const currentIndex = Math.min(modules.length - 1, Math.floor(completed / 5));
  const currentModule = modules[currentIndex];
  const levelLabel = completed >= 35 ? 'Advanced' : completed >= 15 ? 'Intermediate' : 'Beginner';
  const averageAccuracy = profile?.averageAccuracy ?? (sessions?.length ? Math.round(sessions.reduce((sum, row) => sum + row.accuracy_percentage, 0) / sessions.length) : 0);
  const totalSeconds = (sessions ?? []).reduce((sum, row) => sum + (row.duration_seconds ?? 0), 0);
  const displayTime = totalSeconds >= 3600 ? `${Math.floor(totalSeconds / 3600)}h ${Math.round((totalSeconds % 3600) / 60)}m` : `${Math.max(0, Math.round(totalSeconds / 60))}m`;
  const unlocked = new Set(Array.isArray(childProgress?.achievements) ? childProgress.achievements.map((item) => item.id) : childProgress?.achievements ? Object.keys(childProgress.achievements) : []);
  const weeklyDays = useMemo(() => Array.from({ length: 7 }, (_, index) => { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - (6 - index)); const practiced = (sessions ?? []).some((row) => new Date(row.created_at).toDateString() === date.toDateString()); return { date, practiced }; }), [sessions]);
  const tabItems = [{ id: 'modules', label: 'Pag-unlad sa Modyul', icon: BookOpen }, { id: 'activities', label: 'Mga Aktibidad', icon: List }, { id: 'results', label: 'Mga Nakuhang Resulta', icon: Trophy }, { id: 'time', label: 'Mga Tala sa Pagsasanay', icon: Clock3 }] as const;

  return <div className="parent-progress-reference">
    <header className="parent-progress-hero"><div><p>READING ANALYTICS</p><h1>Ulat ng Progreso</h1><span>Malinaw na buod ng pag-unlad sa pagbasa.</span></div>{children?.length ? <label><b>Anak</b><span className="progress-child-avatar">{activeChild?.name.charAt(0).toUpperCase()}</span><strong>{activeChild?.name}</strong><ChevronDown size={18} /><select aria-label="Piliin ang anak" value={activeChildId ?? ''} onChange={(event) => setSelectedChildId(event.target.value)}>{children.map((child) => <option key={child.id} value={child.id}>{child.name}</option>)}</select></label> : null}</header>
    {isLoading ? <div className="progress-loading">Binubuo ang ulat...</div> : <>
      <section className="progress-top-grid"><article className="progress-overview"><div className="progress-donut" style={{ '--progress': `${progressPercent * 3.6}deg` } as React.CSSProperties}><div><b>{progressPercent}%</b><small>{completed} / {totalActivities}<br />aktibidad</small></div></div><div className="progress-overview-data"><h2>Kabuuang Progreso</h2><p>Nakumpletong aktibidad mula sa kabuuang modyul.</p><div><span><BookOpen size={22} /><b>{completed} / {totalActivities}</b><small>Mga Aktibidad</small></span><span><Star size={22} /><b>{averageAccuracy}%</b><small>Average Score</small></span><span><BarChart3 size={22} /><b>{levelLabel}</b><small>Kasalukuyang Level</small></span></div></div></article><article className="progress-current"><h2>Kasalukuyang Modyul</h2><div><span className="progress-module-art"><img src={currentModuleArt} alt="" /></span><p><b>{currentModule}</b><small>Modyul {currentIndex + 1} • {Math.min(5, completed % 5)} / 5 aktibidad</small><i><em style={{ width: `${Math.min(100, (completed % 5) * 20)}%` }} /></i><strong>{Math.min(100, (completed % 5) * 20)}%</strong><Link to="/parent/progress">Ipagpatuloy ang Pagsasanay <ChevronRight size={16} /></Link></p></div></article></section>
      <nav className="progress-tabs" aria-label="Mga bahagi ng ulat">{tabItems.map((tab) => { const Icon = tab.icon; return <button type="button" key={tab.id} onClick={() => setSearchParams(tab.id === 'modules' ? {} : { tab: tab.id })} className={activeTab === tab.id ? 'active' : ''}><Icon size={21} />{tab.label}</button>; })}</nav>
      <div className="progress-main-grid"><section className="progress-panel progress-module-panel"><div className="progress-panel-title"><BookOpen size={26} /><div><h2>{activeTab === 'modules' ? 'Pag-unlad sa Bawat Modyul' : tabItems.find((tab) => tab.id === activeTab)?.label}</h2><p>{activeTab === 'modules' ? `Tingnan ang kumpletong listahan ng modyul at ang progreso ni ${activeChild?.name ?? 'iyong anak'}.` : 'Buod mula sa kasalukuyang practice records.'}</p></div></div>{activeTab === 'modules' ? <ol>{modules.map((module, index) => { const done = index < currentIndex; const active = index === currentIndex; const value = done ? 100 : active ? Math.min(100, (completed % 5) * 20) : 0; return <li key={module} className={`progress-module-card module-tone-${index % 4} ${done ? 'is-done' : active ? 'is-active' : ''}`}><span>{index + 1}</span><div><b>{module}</b><small>{done ? '5 / 5 aktibidad' : active ? `${Math.min(5, completed % 5)} / 5 aktibidad` : '0 / 5 aktibidad'}</small></div><em className={done ? 'done' : active ? 'active' : ''}>{done ? '✓ Tapos na' : active ? '★ Isinasagawa' : index > currentIndex + 2 ? '🔒 Naka-lock' : '◷ Hindi Pa Nagsisimula'}</em><i><u style={{ width: `${value}%` }} /></i><strong>{value}%</strong><Link to="/parent/progress" aria-label={`Buksan ang ${module}`}><ChevronRight size={19} /></Link></li>; })}</ol> : <div className="progress-tab-summary"><Sparkles size={32} /><h3>{activeTab === 'activities' ? `${sessions?.length ?? 0} naitala na practice sessions` : activeTab === 'results' ? `${unlocked.size} badge ang nakamit` : `${displayTime} kabuuang oras ng pagsasanay`}</h3><p>Ang mas detalyadong impormasyon ay nakabase sa aktuwal na activities ni {activeChild?.name ?? 'iyong anak'}.</p></div>}</section><aside className="progress-panel progress-activity"><div className="progress-panel-title"><Award size={25} /><div><h2>Kamakailang Aktibidad</h2><p>Mga huling gawain ni {activeChild?.name ?? 'iyong anak'} sa pagbasa.</p></div></div><div className="progress-timeline">{sessions?.length ? sessions.slice(0, 5).map((session, index) => <div key={`${session.created_at}-${index}`}><span className={session.is_correct ? 'complete' : 'playing'}>{session.is_correct ? <CheckCircle2 size={16} /> : <PlayCircle size={16} />}</span><p><b>{session.is_correct ? 'Tapos ang Activity' : 'Sinimulan ang Activity'}</b><small>{currentModule} • {session.accuracy_percentage}% kawastuhan</small></p><time>{new Date(session.created_at).toLocaleDateString('fil-PH', { month: 'short', day: 'numeric', year: 'numeric' })}</time></div>) : <div className="parent-tab-empty"><img src={noActivitiesArt} alt="" /><p className="progress-empty">Wala pang aktibidad.</p></div>}</div><Link className="progress-all-activity" to="/parent/progress">Tingnan ang Lahat ng Aktibidad <ChevronRight size={17} /></Link></aside></div>
      <section className="progress-bottom-grid"><article><CalendarDays size={27} /><div><h2>Pagsasanay ngayong Linggo</h2><p>Bilang ng araw na nag-practice si {activeChild?.name ?? 'iyong anak'}.</p></div><section>{weeklyDays.map(({ date, practiced }) => <span className={practiced ? 'practiced' : ''} key={date.toISOString()}><small>{date.toLocaleDateString('fil-PH', { weekday: 'short' })}</small><b>{date.getDate()}</b>{practiced ? <CheckCircle2 size={14} /> : <i />}</span>)}</section></article><article><Clock3 size={27} /><div><h2>Kabuuang Oras ng Pagsasanay</h2><p>Kabuuang oras na ginugol sa pagbabasa.</p></div><strong>{displayTime}</strong></article><article><Star size={28} /><div><h2>Mga Nakuhang Badge</h2><p>{unlocked.size} sa {BADGE_CATALOG.length} badge ang nakuha.</p></div><section className="progress-badge-row">{BADGE_CATALOG.slice(0, 6).map((badge) => <span className={unlocked.has(badge.id) ? 'earned' : ''} key={badge.id}>{unlocked.has(badge.id) ? <img src={badge.image} alt={badge.title} /> : <Lock size={16} />}</span>)}<Link to="/parent/progress"><ChevronRight size={20} /></Link></section></article></section>
    </>}</div>;
}
