import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CalendarDays, ChevronLeft, ChevronRight, Clock3, Lightbulb, List, Plus } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { supabase } from '../../lib/supabaseClient';
import { useAuth } from '../../lib/auth/AuthContext';
import noActivitiesArt from '../../assets/parent/no activities.png';

interface Child { id: string; name: string; }
interface Activity { id: string; child_id: string; activity_type: string; title: string; description: string | null; scheduled_date: string; start_time: string | null; end_time: string | null; status: string; }
const types = [{ value: 'reading_lesson', label: 'Module / Lesson', color: 'blue' }, { value: 'practice', label: 'Practice', color: 'green' }, { value: 'reminder', label: 'Assignment', color: 'gold' }, { value: 'appointment', label: 'Reading', color: 'violet' }];
const statuses = [{ value: 'scheduled', label: 'Nakatakda' }, { value: 'in_progress', label: 'Ginagawa' }, { value: 'completed', label: 'Nakumpleto' }, { value: 'missed', label: 'Nalampasan' }];
const toKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const typeFor = (value: string) => types.find((item) => item.value === value) ?? types[0];

export default function Schedule() {
  const { user } = useAuth(); const client = useQueryClient();
  const [searchParams] = useSearchParams();
  const requestedDate = searchParams.get('date');
  const validRequestedDate = requestedDate && /^\d{4}-\d{2}-\d{2}$/.test(requestedDate) ? requestedDate : null;
  const [selectedChild, setSelectedChild] = useState(''); const [month, setMonth] = useState(() => validRequestedDate ? new Date(`${validRequestedDate}T00:00:00`) : new Date(new Date().getFullYear(), new Date().getMonth(), 1)); const [mode, setMode] = useState<'Buwan' | 'Linggo' | 'Araw'>('Buwan'); const [selectedDate, setSelectedDate] = useState<string | null>(validRequestedDate); const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ activity_type: 'reading_lesson', title: '', scheduled_date: '', start_time: '', description: '' });
  const { data: children } = useQuery({ queryKey: ['parent-children', user?.id], queryFn: async () => { const { data, error } = await supabase.from('children').select('id,name').order('name'); if (error) throw error; return data as Child[]; }, enabled: Boolean(user) });
  const activeChild = selectedChild || children?.[0]?.id || '';
  const { data: schedule = [] } = useQuery({ queryKey: ['parent-schedule', user?.id], queryFn: async () => { const { data, error } = await supabase.from('scheduled_activities').select('id,child_id,activity_type,title,description,scheduled_date,start_time,end_time,status').order('scheduled_date'); if (error) throw error; return data as Activity[]; }, enabled: Boolean(user) });
  const save = useMutation({ mutationFn: async () => { if (!activeChild || !form.title || !form.scheduled_date) throw new Error('Kumpletuhin ang anak, pamagat, at petsa.'); const { error } = await supabase.from('scheduled_activities').insert({ child_id: activeChild, created_by: 'parent', created_by_auth_uid: user!.id, ...form, description: form.description || null, start_time: form.start_time || null, status: 'scheduled' }); if (error) throw error; }, onSuccess: () => { setShowForm(false); setForm({ activity_type: 'reading_lesson', title: '', scheduled_date: '', start_time: '', description: '' }); client.invalidateQueries({ queryKey: ['parent-schedule'] }); } });
  const update = useMutation({ mutationFn: async ({ id, status }: { id: string; status: string }) => { const { error } = await supabase.from('scheduled_activities').update({ status }).eq('id', id); if (error) throw error; }, onSuccess: () => client.invalidateQueries({ queryKey: ['parent-schedule'] }) });
  const filtered = schedule.filter((item) => !activeChild || item.child_id === activeChild); const events = filtered.reduce<Record<string, Activity[]>>((all, item) => { (all[item.scheduled_date] ??= []).push(item); return all; }, {});
  const first = new Date(month.getFullYear(), month.getMonth(), 1); const start = new Date(first); start.setDate(start.getDate() - ((first.getDay() + 6) % 7)); const days = Array.from({ length: 42 }, (_, index) => { const date = new Date(start); date.setDate(start.getDate() + index); return date; }); const today = toKey(new Date());
  const dateLabel = month.toLocaleDateString('fil-PH', { month: 'long', year: 'numeric' });
  return <div className="calendar-reference">
    <header className="calendar-reference-hero"><div><p>PLANO NG PAMILYA</p><h1>Kalendaryo at Iskedyul</h1><span>Tingnan ang mga aktibidad, takdang-aralin, at mahahalagang petsa ng inyong anak.</span></div><label><b>Anak</b><i>{(children?.find((child) => child.id === activeChild)?.name ?? 'A').charAt(0)}</i><strong>{children?.find((child) => child.id === activeChild)?.name ?? 'Piliin ang Anak'}</strong><ChevronRight size={17} /><select value={activeChild} onChange={(event) => setSelectedChild(event.target.value)}>{children?.map((child) => <option key={child.id} value={child.id}>{child.name}</option>)}</select></label></header>
    <div className="calendar-reference-grid"><div className="calendar-reference-left"><section className="calendar-board"><div className="calendar-toolbar"><button type="button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))}><ChevronLeft /></button><h2>{dateLabel}</h2><button type="button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))}><ChevronRight /></button><span /><div>{(['Buwan', 'Linggo', 'Araw'] as const).map((item) => <button type="button" className={mode === item ? 'active' : ''} onClick={() => setMode(item)} key={item}>{item === 'Buwan' && <CalendarDays size={17} />}{item}</button>)}</div></div><div className="calendar-weekdays">{['Lun', 'Mar', 'Miy', 'Huw', 'Biy', 'Sab', 'Araw'].map((day) => <b key={day}>{day}</b>)}</div><div className={`calendar-day-grid ${mode.toLowerCase()}`}>{days.map((date) => { const key = toKey(date); const inMonth = date.getMonth() === month.getMonth(); const dayEvents = events[key] ?? []; return <button type="button" key={key} className={`${inMonth ? '' : 'outside'} ${key === today ? 'today' : ''} ${selectedDate === key ? 'selected' : ''}`} onClick={() => setSelectedDate(key)}><strong>{date.getDate()}</strong>{dayEvents.slice(0, 2).map((event) => <small className={typeFor(event.activity_type).color} key={event.id}>● {event.title}</small>)}</button>; })}</div><div className="calendar-legend">{types.map((type) => <span className={type.color} key={type.value}>● {type.label}</span>)}</div></section>
      <section className="calendar-details"><div><List size={25} /><h2>Mga Detalye ng Aktibidad</h2><button type="button" onClick={() => setShowForm((value) => !value)}><Plus size={16} /> Magdagdag</button></div>{showForm && <form onSubmit={(event) => { event.preventDefault(); save.mutate(); }}><select value={form.activity_type} onChange={(event) => setForm({ ...form, activity_type: event.target.value })}>{types.map((type) => <option key={type.value} value={type.value}>{type.label}</option>)}</select><input placeholder="Pamagat ng aktibidad" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /><input type="date" value={form.scheduled_date} onChange={(event) => setForm({ ...form, scheduled_date: event.target.value })} /><input type="time" value={form.start_time} onChange={(event) => setForm({ ...form, start_time: event.target.value })} /><button disabled={save.isPending}>{save.isPending ? 'Sine-save...' : 'I-save ang Aktibidad'}</button></form>}<div className="calendar-table"><header><b>Petsa</b><b>Uri</b><b>Pamagat</b><b>Modyul</b><b>Status</b><b>Aksyon</b></header>{filtered.filter((item) => !selectedDate || item.scheduled_date === selectedDate).slice(0, 8).map((item) => <div key={item.id}><span>{new Date(item.scheduled_date).toLocaleDateString('fil-PH', { month: 'short', day: 'numeric', year: 'numeric' })}</span><em className={typeFor(item.activity_type).color}>● {typeFor(item.activity_type).label}</em><strong>{item.title}</strong><span>{item.description ?? 'Reading activity'}</span><select value={item.status} onChange={(event) => update.mutate({ id: item.id, status: event.target.value })}>{statuses.map((status) => <option key={status.value} value={status.value}>{status.label}</option>)}</select><button type="button" onClick={() => setSelectedDate(item.scheduled_date)}>Tingnan <ChevronRight size={14} /></button></div>)}{!filtered.length && <div className="calendar-no-data parent-tab-empty"><img src={noActivitiesArt} alt="" />Wala pang aktibidad. I-click ang “Magdagdag” upang gumawa ng iskedyul.</div>}</div></section></div>
      <aside className="calendar-reference-side"><section><header><CalendarDays size={26} /><h2>Mga Paparating na Aktibidad</h2></header>{filtered.filter((item) => item.status === 'scheduled').slice(0, 4).map((item) => <button type="button" key={item.id} onClick={() => { setSelectedDate(item.scheduled_date); setMonth(new Date(`${item.scheduled_date}T00:00:00`)); }}><time className={typeFor(item.activity_type).color}><b>{new Date(item.scheduled_date).toLocaleDateString('fil-PH', { month: 'short' }).toUpperCase()}</b><strong>{new Date(item.scheduled_date).getDate()}</strong></time><span><b>{item.title}</b><small>{item.start_time ? <><Clock3 size={13} /> {item.start_time}</> : 'Buong araw'}</small></span><em>Nakatakda</em></button>)}{!filtered.length && <p>Wala pang paparating na aktibidad.</p>}</section><section className="calendar-reminder"><header><Lightbulb size={26} /><h2>Mga Paalala</h2></header><p>Panatilihing updated ang iskedyul upang masubaybayan ang progreso ng inyong anak.</p></section></aside></div>
  </div>;
}
