import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api } from '../../lib/api';
import { cardStyle } from '../../lib/cardStyle';

interface Analytics { roleCounts: Record<string, number>; totals: { studentAccounts: number; users: number; totalXp: number; badgeUnlockCount: number; practiceSessions: number } }
interface Student { id: string; name: string; email: string | null; gradeLevel: number | null; lastLoginAt: string | null; progress: { level: string | null; accuracy: number | null; attempts: number; activitiesCompleted: number; xp: number; streak: number; updatedAt: string | null } }
const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat('fil-PH', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Manila' }).format(new Date(value)) : 'Wala pa';

function StudentModal({ close }: { close: () => void }) {
  const { data, error, isLoading } = useQuery({ queryKey: ['admin-analytics-students'], queryFn: () => api<{ students: Student[] }>('/admin/analytics/students', { auth: true }) });
  return <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-black/55 p-4">
    <section className="flex max-h-[88vh] w-full max-w-6xl flex-col overflow-hidden rounded-3xl bg-[var(--color-surface)] shadow-raised">
      <header className="flex justify-between gap-4 border-b p-5"><div><p className="text-xs font-extrabold tracking-[.12em] text-[var(--color-primary)] uppercase">Student accounts</p><h2 className="text-2xl font-extrabold">Detalye at progreso ng mag-aaral</h2></div><button type="button" onClick={close} className="rounded-xl border px-3 py-2 font-bold">Isara</button></header>
      <div className="overflow-y-auto p-5">{isLoading ? <p>Nilo-load ang mga student account...</p> : error ? <p role="alert" className="rounded-2xl bg-[var(--color-danger-soft)] p-4 text-[var(--color-danger)]">Hindi ma-load ang student details: {(error as Error).message}</p> : data?.students.length ? <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">{data.students.map((student) => <article key={student.id} className="rounded-3xl border p-5 shadow-card" style={cardStyle(student.progress.accuracy !== null && student.progress.accuracy < 70 ? '--color-brand-coral' : '--color-brand-sage', 6, 22)}><div className="flex justify-between gap-3"><div className="min-w-0"><h3 className="truncate text-lg font-extrabold">{student.name}</h3><p className="truncate text-xs text-[var(--color-text-muted)]">{student.email || 'Walang email'}</p></div><span className="rounded-full bg-white/75 px-2 py-1 text-xs font-bold">Grade {student.gradeLevel ?? '—'}</span></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><div className="rounded-2xl bg-white/65 p-2"><b>{student.progress.accuracy === null ? '—' : student.progress.accuracy + '%'}</b><p className="text-[10px]">Kawastuhan</p></div><div className="rounded-2xl bg-white/65 p-2"><b>{student.progress.activitiesCompleted}</b><p className="text-[10px]">Gawain</p></div><div className="rounded-2xl bg-white/65 p-2"><b>{student.progress.streak}</b><p className="text-[10px]">Streak</p></div></div><dl className="mt-4 space-y-1 text-sm"><div className="flex justify-between gap-3"><dt>Reading level</dt><dd className="font-bold">{student.progress.level || 'Wala pa'}</dd></div><div className="flex justify-between gap-3"><dt>XP / attempts</dt><dd className="font-bold">{student.progress.xp.toLocaleString()} / {student.progress.attempts}</dd></div><div className="flex justify-between gap-3"><dt>Huling progress</dt><dd className="text-right text-xs">{formatDate(student.progress.updatedAt)}</dd></div><div className="flex justify-between gap-3"><dt>Huling login</dt><dd className="text-right text-xs">{formatDate(student.lastLoginAt)}</dd></div></dl></article>)}</div> : <p className="rounded-2xl border border-dashed p-8 text-center">Wala pang student account.</p>}</div>
    </section>
  </div>;
}

export default function AdminAnalytics() {
  const [showStudents, setShowStudents] = useState(false);
  const { data, isLoading, error } = useQuery({ queryKey: ['admin-analytics'], queryFn: () => api<Analytics>('/admin/analytics', { auth: true }) });
  const cards = data ? [{ label: 'Mga gumagamit', value: data.totals.users, note: 'Lahat ng account', color: '--color-brand-lavender' }, { label: 'Student accounts', value: data.totals.studentAccounts, note: 'Pindutin para sa detalye', color: '--color-brand-sage' }, { label: 'Pagsasanay', value: data.totals.practiceSessions, note: 'Mga sesyon ng pagsasanay', color: '--color-brand-teal' }, { label: 'Kabuuang XP', value: data.totals.totalXp, note: 'Puntos sa pagkatuto', color: '--color-brand-sun' }, { label: 'Mga Parangal', value: data.totals.badgeUnlockCount, note: 'Mga nakuhang parangal', color: '--color-brand-violet' }] : [];
  return <div className="flex min-w-0 flex-col gap-6"><header><p className="text-xs font-extrabold tracking-[.12em] text-[var(--color-primary)] uppercase">Pananaw sa sistema</p><h1 className="text-2xl font-extrabold sm:text-3xl">Pagsusuri</h1><p className="mt-1 text-sm text-[var(--color-text-muted)]">Buod ng mga account at pakikibahagi sa pagkatuto.</p></header>{isLoading ? <div className="grid grid-cols-2 gap-3 lg:grid-cols-5">{Array.from({ length: 5 }, (_, index) => <div key={index} className="h-28 animate-pulse rounded-3xl border bg-white/45" />)}</div> : error ? <p role="alert" className="rounded-2xl bg-[var(--color-danger-soft)] p-4 text-[var(--color-danger)]">Hindi ma-load ang analytics: {(error as Error).message}</p> : <section className="grid grid-cols-2 gap-3 lg:grid-cols-5">{cards.map((card) => card.label === 'Student accounts' ? <button key={card.label} type="button" onClick={() => setShowStudents(true)} className="rounded-3xl border p-4 text-left shadow-card transition hover:-translate-y-0.5 hover:shadow-raised" style={cardStyle(card.color, 7, 25)}><p className="text-3xl font-extrabold">{card.value.toLocaleString()}</p><p className="mt-2 text-sm font-bold">{card.label}</p><p className="mt-1 text-xs text-[var(--color-text-muted)]">{card.note}</p></button> : <article key={card.label} className="rounded-3xl border p-4 shadow-card" style={cardStyle(card.color, 7, 25)}><p className="text-3xl font-extrabold">{card.value.toLocaleString()}</p><p className="mt-2 text-sm font-bold">{card.label}</p><p className="mt-1 text-xs text-[var(--color-text-muted)]">{card.note}</p></article>)}</section>}{showStudents && <StudentModal close={() => setShowStudents(false)} />}</div>;
}
