import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api } from '../../lib/api';

type Module={id:string;number:number;title:string};
type Student={id:string;name:string;email:string|null;gradeLevel:number|null;progress:{level:string|null;accuracy:number|null;activitiesCompleted:number;streak:number;xp:number;attempts:number;completedModules:Module[]}};
type Data={enrollmentTrend:{month:string;count:number}[];usageTrend:{month:string;count:number}[];totals:{studentAccounts:number;users:number;practiceSessions:number;totalXp:number;badgeUnlockCount:number}};
function Students({close}:{close:()=>void}){const q=useQuery({queryKey:['students'],queryFn:()=>api<{students:Student[]}>('/admin/analytics/students',{auth:true})});const[search,setSearch]=useState('');const[page,setPage]=useState(1);const rows=(q.data?.students??[]).filter(s=>s.name.toLowerCase().includes(search.toLowerCase()));const shown=rows.slice((page-1)*10,page*10);return <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><section className="max-h-[88vh] w-full max-w-6xl overflow-auto rounded-3xl bg-white"><header className="flex justify-between border-b p-6"><h2 className="text-2xl font-bold">Student Accounts</h2><button onClick={close}>Isara</button></header><div className="p-6"><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Hanapin ang student..." className="mb-4 w-full rounded-xl border p-3"/><table className="w-full min-w-[800px] text-left"><thead><tr><th>Pangalan</th><th>Grade</th><th>Level</th><th>Accuracy</th><th>Modules</th><th>XP</th><th>Streak</th></tr></thead><tbody>{shown.map(s=><tr key={s.id} className="border-t"><td className="py-3"><b>{s.name}</b><small className="block">{s.email}</small></td><td>{s.gradeLevel}</td><td>{s.progress.level||'—'}</td><td>{s.progress.accuracy??'—'}</td><td>{s.progress.completedModules.length}</td><td>{s.progress.xp}</td><td>{s.progress.streak}</td></tr>)}</tbody></table><div className="mt-4 flex justify-between"><span>{rows.length} students</span><div><button disabled={page===1} onClick={()=>setPage(page-1)}>Nakaraan</button><span className="px-3">{page}</span><button disabled={page*10>=rows.length} onClick={()=>setPage(page+1)}>Susunod</button></div></div></div></section></div>}
export default function Analytics(){const[open,setOpen]=useState(false);const q=useQuery({queryKey:['analytics'],queryFn:()=>api<Data>('/admin/analytics',{auth:true})});const chart=(title:string,rows:{month:string;count:number}[],accent:string)=> <section className="rounded-3xl border border-[var(--color-border)] bg-white/80 p-5 shadow-card"><p className="text-xs font-bold tracking-widest text-[var(--color-text-muted)]">TREND</p><h2 className="mt-1 text-xl font-extrabold">{title}</h2><div className="mt-4 h-72">{rows.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={rows}><CartesianGrid strokeDasharray="4 4" vertical={false}/><XAxis dataKey="month"/><YAxis allowDecimals={false}/><Tooltip/><Area dataKey="count" stroke={accent} strokeWidth={3} fill={accent} fillOpacity={0.18}/></AreaChart></ResponsiveContainer>:<p className="grid h-full place-items-center text-sm text-[var(--color-text-muted)]">Wala pang datos.</p>}</div></section>;return <div className="mx-auto flex w-full max-w-[1500px] flex-col gap-6 pb-8"><header className="rounded-3xl border p-6 shadow-card"><p className="text-xs font-extrabold tracking-widest text-[var(--color-primary)]">SYSTEM OVERVIEW</p><h1 className="mt-2 text-3xl font-extrabold">Pagsusuri</h1><p className="mt-1 text-sm text-[var(--color-text-muted)]">Malinaw na buod ng users at learning activity.</p></header>{q.data&&<><div className="grid grid-cols-2 gap-4 lg:grid-cols-5">{[['Mga gumagamit',q.data.totals.users],['Student accounts',q.data.totals.studentAccounts],['Pagsasanay',q.data.totals.practiceSessions],['Kabuuang XP',q.data.totals.totalXp],['Mga Parangal',q.data.totals.badgeUnlockCount]].map(([label,value])=>label==='Student accounts'?<button key={String(label)} onClick={()=>setOpen(true)} className="rounded-3xl border bg-white p-5 text-left shadow-card transition hover:-translate-y-1 hover:shadow-raised"><b className="text-3xl">{value}</b><p className="mt-2 font-bold">{label}</p><small>Pindutin para sa detalye</small></button>:<article key={String(label)} className="rounded-3xl border bg-white p-5 shadow-card"><b className="text-3xl">{value}</b><p className="mt-2 font-bold">{label}</p></article>)}</div><div className="grid gap-5 xl:grid-cols-2">{chart('Pagpapalista bawat buwan',q.data.enrollmentTrend,'#6d4aff')}{chart('Paggamit ng pagsasanay',q.data.usageTrend,'#0f9f98')}</div></>}{open&&<Students close={()=>setOpen(false)}/>}</div>}
