import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api } from '../../lib/api';
import { cardStyle } from '../../lib/cardStyle';

type Log = { id: string; actor_name: string | null; actor_role: string | null; action: string; module: string; status: 'successful' | 'failed'; metadata: { platform?: string; device?: string; sessionStatus?: string }; created_at: string };
const time = (value: string) => new Intl.DateTimeFormat('fil-PH', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Manila' }).format(new Date(value));

export default function AuditLogs() {
  const [search, setSearch] = useState(''); const [role, setRole] = useState(''); const [page, setPage] = useState(1); const [selected, setSelected] = useState<Log | null>(null);
  const params = new URLSearchParams({ page: String(page), pageSize: '25' }); if (search) params.set('search', search); if (role) params.set('role', role);
  const query = useQuery({ queryKey: ['audit', params.toString()], queryFn: () => api<{ logs: Log[]; total: number; pageSize: number }>(`/admin/audit-logs?${params}`, { auth: true }) });
  const total = query.data?.total || 0; const pages = Math.max(1, Math.ceil(total / (query.data?.pageSize || 25)));
  return <div className="mx-auto flex max-w-[1500px] flex-col gap-5 pb-8"><header className="rounded-3xl border p-6 shadow-card" style={cardStyle('--color-brand-lavender', 7, 25)}><p className="text-xs font-extrabold tracking-[.14em] text-[var(--color-primary)] uppercase">Monitoring at seguridad</p><h1 className="mt-2 text-3xl font-extrabold">Audit Trail</h1><p className="mt-1 text-sm text-[var(--color-text-muted)]">Append-only record ng transaksyon, login session, platform, at device kapag available.</p></header>
    <section className="flex flex-wrap gap-3 rounded-3xl border p-4 shadow-card" style={cardStyle('--color-brand-sage', 5, 22)}><input className="min-h-11 rounded-xl border px-3" value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Pangalan o aksyon..." /><select className="min-h-11 rounded-xl border px-3" value={role} onChange={(event) => { setRole(event.target.value); setPage(1); }}><option value="">Lahat ng user</option><option value="student">Mga mag-aaral</option><option value="parent">Mga magulang</option><option value="teacher">Mga guro</option></select></section>
    {query.error && <p role="alert" className="rounded-2xl bg-[var(--color-danger-soft)] p-4 text-[var(--color-danger)]">Hindi ma-load ang Audit Trail.</p>}<section className="overflow-hidden rounded-3xl border bg-white/70 shadow-card"><div className="flex justify-between border-b p-4"><b>Mga aktibidad</b><span className="text-sm text-[var(--color-text-muted)]">{total} record</span></div><div className="max-h-[62vh] overflow-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="sticky top-0 bg-[var(--color-brand-navy)] text-white"><tr><th className="p-4">Oras</th><th className="p-4">User / Role</th><th className="p-4">Aksyon</th><th className="p-4">Platform</th><th className="p-4">Session</th><th className="p-4">Status</th><th /></tr></thead><tbody>{query.isLoading ? Array.from({ length: 6 }, (_, index) => <tr key={index}><td colSpan={7} className="p-4"><div className="h-7 animate-pulse rounded bg-[var(--color-primary-soft)]" /></td></tr>) : query.data?.logs.map((log) => <tr key={log.id} className="border-t hover:bg-[var(--color-primary-soft)]/30"><td className="p-4">{time(log.created_at)}</td><td className="p-4"><b>{log.actor_name || 'System'}</b><p className="text-xs capitalize">{log.actor_role || 'system'}</p></td><td className="p-4">{log.action.replace('.', ' · ')}</td><td className="p-4"><span className="rounded-full border bg-white/70 px-2 py-1 font-bold">{log.metadata.platform || '—'}</span></td><td className="p-4">{log.metadata.sessionStatus || '—'}</td><td className="p-4">{log.status === 'successful' ? '✓ Matagumpay' : '! Nabigo'}</td><td className="p-4"><button onClick={() => setSelected(log)} className="font-bold text-[var(--color-primary)]">Detalye</button></td></tr>)}{!query.isLoading && !query.data?.logs.length && <tr><td colSpan={7} className="p-12 text-center">Walang tumugmang record.</td></tr>}</tbody></table></div><footer className="flex justify-between border-t p-4"><span>Page {page} ng {pages}</span><div className="flex gap-2"><button disabled={page === 1} onClick={() => setPage(page - 1)} className="rounded-xl border px-4 py-2 disabled:opacity-40">← Nakaraan</button><button disabled={page >= pages} onClick={() => setPage(page + 1)} className="rounded-xl bg-[var(--color-brand-navy)] px-4 py-2 text-white disabled:opacity-40">Susunod →</button></div></footer></section>
    {selected && <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><article className="w-full max-w-2xl rounded-3xl bg-[var(--color-surface)] p-6 shadow-raised"><div className="flex justify-between"><h2 className="text-xl font-extrabold">Detalye ng transaksyon</h2><button onClick={() => setSelected(null)} className="rounded-xl border px-3">Isara</button></div><dl className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt>User</dt><dd className="font-bold">{selected.actor_name || 'System'}</dd></div><div><dt>Role</dt><dd className="capitalize">{selected.actor_role || 'system'}</dd></div><div><dt>Oras</dt><dd>{time(selected.created_at)}</dd></div><div><dt>Platform</dt><dd>{selected.metadata.platform || '—'}</dd></div><div className="col-span-2"><dt>Device/browser</dt><dd className="break-all text-xs">{selected.metadata.device || 'Hindi available'}</dd></div></dl></article></div>}</div>;
}
