import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api } from '../../lib/api';
import { cardStyle } from '../../lib/cardStyle';

interface AuditLog { id: string; actor_role: string | null; actor_name: string | null; action: string; module: string; record_id: string | null; status: 'successful' | 'failed'; metadata: Record<string, unknown>; created_at: string }
const inputClass = 'min-h-10 rounded-xl border border-[var(--color-border)] bg-white/70 px-3 text-sm outline-none focus:border-[var(--color-primary)]';

export default function AuditLogs() {
  const [search, setSearch] = useState(''); const [role, setRole] = useState(''); const [status, setStatus] = useState(''); const [module, setModule] = useState(''); const [action, setAction] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [order, setOrder] = useState('desc'); const [page, setPage] = useState(1); const [selected, setSelected] = useState<AuditLog | null>(null);
  const params = new URLSearchParams({ page: String(page), pageSize: '25' });
  params.set('order', order); if (search) params.set('search', search); if (role) params.set('actor_role', role); if (status) params.set('status', status); if (module) params.set('module', module); if (action) params.set('action', action); if (from) params.set('from', from); if (to) params.set('to', to);
  const { data, isLoading, error } = useQuery({ queryKey: ['admin-audit-logs', params.toString()], queryFn: () => api<{ logs: AuditLog[]; total: number; pageSize: number }>(`/admin/audit-logs?${params}`, { auth: true }) });
  const totalPages = Math.max(1, Math.ceil((data?.total ?? 0) / (data?.pageSize ?? 25)));
  const reset = () => { setSearch(''); setRole(''); setStatus(''); setModule(''); setAction(''); setFrom(''); setTo(''); setOrder('desc'); setPage(1); };
  return <div className="flex flex-col gap-5"><header><p className="text-xs font-extrabold tracking-[.12em] text-[var(--color-primary)] uppercase">Monitoring</p><h1 className="text-2xl font-extrabold sm:text-3xl">Audit Trail</h1><p className="mt-1 text-sm text-[var(--color-text-muted)]">Append-only record ng mahahalagang transaksyon sa system.</p></header>
    <section className="grid gap-3 rounded-3xl border p-4 shadow-card sm:grid-cols-2 lg:grid-cols-4" style={cardStyle('--color-brand-sage', 4, 18)}><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} className={inputClass} placeholder="Pangalan o aksyon..." /><select value={role} onChange={(e) => { setRole(e.target.value); setPage(1); }} className={inputClass}><option value="">Lahat ng role</option><option>student</option><option>parent</option><option>teacher</option><option>admin</option></select><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }} className={inputClass}><option value="">Lahat ng status</option><option value="successful">Matagumpay</option><option value="failed">Nabigo</option></select><input value={module} onChange={(e) => { setModule(e.target.value); setPage(1); }} className={inputClass} placeholder="Module (hal. student)" /><input value={action} onChange={(e) => { setAction(e.target.value); setPage(1); }} className={inputClass} placeholder="Eksaktong aksyon" /><label className="text-xs font-bold">Mula<input type="date" value={from} onChange={(e) => { setFrom(e.target.value); setPage(1); }} className={`${inputClass} mt-1 w-full`} /></label><label className="text-xs font-bold">Hanggang<input type="date" value={to} onChange={(e) => { setTo(e.target.value); setPage(1); }} className={`${inputClass} mt-1 w-full`} /></label><select value={order} onChange={(e) => { setOrder(e.target.value); setPage(1); }} className={`${inputClass} self-end`}><option value="desc">Pinakabago muna</option><option value="asc">Pinakaluma muna</option></select><button type="button" onClick={reset} className="min-h-10 self-end rounded-xl border bg-white/65 px-4 text-sm font-bold">I-reset</button></section>
    {error && <p role="alert" className="rounded-xl bg-[var(--color-danger-soft)] p-3 text-sm text-[var(--color-danger)]">{(error as Error).message}</p>}
    <section className="overflow-hidden rounded-3xl border bg-white/55 shadow-card"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[var(--color-brand-navy)] text-white"><tr><th className="p-4">Oras</th><th className="p-4">Gumawa</th><th className="p-4">Aksyon</th><th className="p-4">Module</th><th className="p-4">Status</th><th className="p-4" /></tr></thead><tbody>{isLoading ? <tr><td colSpan={6} className="p-8 text-center">Naglo-load...</td></tr> : (data?.logs ?? []).map((log) => <tr key={log.id} className="border-t"><td className="p-4 whitespace-nowrap">{new Date(log.created_at).toLocaleString('fil-PH')}</td><td className="p-4"><p className="font-bold">{log.actor_name || 'System'}</p><p className="text-xs capitalize text-[var(--color-text-muted)]">{log.actor_role || 'system'}</p></td><td className="p-4 font-semibold">{log.action}</td><td className="p-4">{log.module}</td><td className="p-4"><span className={`rounded-full px-2 py-1 text-xs font-bold ${log.status === 'successful' ? 'bg-[var(--color-success-soft)] text-[var(--color-success)]' : 'bg-[var(--color-danger-soft)] text-[var(--color-danger)]'}`}>{log.status === 'successful' ? 'Matagumpay' : 'Nabigo'}</span></td><td className="p-4"><button type="button" onClick={() => setSelected(log)} className="text-sm font-bold text-[var(--color-primary)]">Detalye</button></td></tr>)}</tbody></table></div></section>
    <footer className="flex items-center justify-between"><p className="text-sm text-[var(--color-text-muted)]">{data?.total ?? 0} record</p><div className="flex gap-2"><button type="button" disabled={page === 1} onClick={() => setPage((p) => p - 1)} className="rounded-full border px-4 py-2 disabled:opacity-40">← Nakaraan</button><span className="self-center text-sm font-bold">{page}/{totalPages}</span><button type="button" disabled={page >= totalPages} onClick={() => setPage((p) => p + 1)} className="rounded-full border px-4 py-2 disabled:opacity-40">Susunod →</button></div></footer>
    {selected && <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-black/45 p-4"><article className="max-h-[85vh] w-full max-w-2xl overflow-auto rounded-3xl bg-[var(--color-surface)] p-6 shadow-raised"><div className="flex justify-between gap-3"><h2 className="text-xl font-extrabold">Detalye ng transaksyon</h2><button type="button" onClick={() => setSelected(null)} className="font-bold">Isara</button></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-[var(--color-text-muted)]">Record ID</dt><dd className="break-all font-semibold">{selected.record_id || '—'}</dd></div><div><dt className="text-[var(--color-text-muted)]">Oras</dt><dd className="font-semibold">{new Date(selected.created_at).toLocaleString('fil-PH')}</dd></div></dl><pre className="mt-4 overflow-auto rounded-xl bg-black/5 p-3 text-xs">{JSON.stringify(selected.metadata, null, 2)}</pre></article></div>}
  </div>;
}
