import { useState } from 'react';
import { useNotifications, type NotificationRow } from '../../lib/useNotifications';
import { cardStyle } from '../../lib/cardStyle';

type Filter = 'all' | 'unread' | 'account' | 'system';
const FILTERS: { value: Filter; label: string }[] = [{ value: 'all', label: 'Lahat' }, { value: 'unread', label: 'Hindi pa nabasa' }, { value: 'account', label: 'Account' }, { value: 'system', label: 'Iba pang update' }];
const ACCOUNT_TYPES = new Set(['account_disabled', 'account_restored', 'student_login']);
function isToday(value: string) { return new Date(value).toDateString() === new Date().toDateString(); }
function formatTime(value: string) { return new Date(value).toLocaleString('fil-PH', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' }); }
function matches(row: NotificationRow, filter: Filter) { if (filter === 'all') return true; if (filter === 'unread') return !row.is_read; if (filter === 'account') return ACCOUNT_TYPES.has(row.type); return !ACCOUNT_TYPES.has(row.type); }
function metaFor(type: string) { if (type === 'account_disabled') return { icon: '⛔', label: 'Mataas', color: '--color-brand-coral' }; if (type === 'account_restored') return { icon: '↩', label: 'Account', color: '--color-brand-sage' }; if (type === 'student_login') return { icon: '●', label: 'Activity', color: '--color-brand-violet' }; return { icon: '🔔', label: 'Update', color: '--color-brand-lavender' }; }

export default function AdminNotifications() {
  const { notifications, unreadCount, isLoading, markAsRead, markAllAsRead } = useNotifications();
  const [filter, setFilter] = useState<Filter>('all');
  const rows = notifications.filter((row) => matches(row, filter));
  const groups = [{ label: 'Ngayon', rows: rows.filter((row) => isToday(row.created_at)) }, { label: 'Mas nauna', rows: rows.filter((row) => !isToday(row.created_at)) }];
  return <div className="flex min-w-0 flex-col gap-5">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-extrabold tracking-[.12em] text-[var(--color-primary)] uppercase">Admin inbox</p><h1 className="text-2xl font-extrabold sm:text-3xl">Mga Abiso</h1><p className="mt-1 text-sm text-[var(--color-text-muted)]">Mga totoong system at account update para sa iyong admin account.</p></div><div className="rounded-2xl border px-5 py-2 text-center shadow-card" style={cardStyle('--color-brand-coral', 7, 25)}><p className="text-2xl font-extrabold text-[var(--color-primary)]">{unreadCount}</p><p className="text-xs font-bold text-[var(--color-text-muted)]">Hindi pa nabasa</p></div></header>
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex max-w-full gap-2 overflow-x-auto pb-1" role="toolbar" aria-label="Salain ang abiso">{FILTERS.map((item) => <button key={item.value} type="button" onClick={() => setFilter(item.value)} aria-pressed={filter === item.value} className={`min-h-10 shrink-0 rounded-full border px-4 text-sm font-bold transition-all ${filter === item.value ? 'border-[var(--color-primary)] bg-[var(--color-primary)] text-white shadow-card' : 'border-[var(--color-border)] bg-white/60 hover:border-[var(--color-primary)]'}`}>{item.label}{item.value === 'unread' && unreadCount ? ` (${unreadCount})` : ''}</button>)}</div>{unreadCount > 0 && <button type="button" onClick={() => markAllAsRead.mutate()} disabled={markAllAsRead.isPending} className="min-h-10 rounded-full border border-[var(--color-primary)] bg-white/65 px-4 text-sm font-extrabold text-[var(--color-primary)] disabled:opacity-50">Markahan lahat na nabasa</button>}</div>
    {isLoading ? <div className="rounded-3xl border bg-white/45 p-10 text-center text-sm text-[var(--color-text-muted)]">Naglo-load ng mga abiso...</div> : rows.length ? <div className="flex flex-col gap-7">{groups.map((group) => group.rows.length > 0 && <section key={group.label}><h2 className="mb-3 text-xs font-extrabold tracking-[.12em] text-[var(--color-text-muted)] uppercase">{group.label} <span className="ml-1 rounded-full bg-white/65 px-2 py-1">{group.rows.length}</span></h2><div className="grid grid-cols-1 gap-3 lg:grid-cols-2">{group.rows.map((row) => { const meta = metaFor(row.type); return <button key={row.id} type="button" onClick={() => !row.is_read && markAsRead.mutate(row.id)} className={`relative flex min-w-0 items-start gap-3 overflow-hidden rounded-3xl border p-4 text-left shadow-card transition-all hover:-translate-y-0.5 hover:shadow-raised sm:p-5 ${row.is_read ? 'opacity-80' : 'border-[var(--color-primary)]/40'}`} style={cardStyle(meta.color, row.is_read ? 4 : 9, row.is_read ? 18 : 30)}>{!row.is_read && <span className="absolute inset-y-0 left-0 w-1 bg-[var(--color-primary)]" />}<span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-white/70 text-lg">{meta.icon}</span><span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-white/70 px-2.5 py-1 text-[.68rem] font-extrabold uppercase">{meta.label}</span>{!row.is_read && <span className="text-[.68rem] font-extrabold text-[var(--color-primary)]">BAGO</span>}</span><span className="mt-2 block font-extrabold leading-snug">{row.title}</span>{(row.body ?? row.message) && <span className="mt-1 block text-sm leading-relaxed text-[var(--color-text-muted)]">{row.body ?? row.message}</span>}<time dateTime={row.created_at} className="mt-2 block text-xs font-semibold text-[var(--color-text-muted)]">{formatTime(row.created_at)}</time></span></button>; })}</div></section>)}</div> : <div className="rounded-3xl border border-dashed border-[var(--color-border)] bg-white/45 p-10 text-center"><p className="text-4xl">🔔</p><h2 className="mt-3 text-xl font-extrabold">Walang abiso sa view na ito</h2><p className="mt-1 text-sm text-[var(--color-text-muted)]">Lalabas rito ang mga update kapag mayroon na.</p></div>}
  </div>;
}
