import parentHero from '../../assets/admin_design/admin-hero-background.png';
import mascot from '../../assets/admin_design/owl-admin-mascot.png';

type Parent = { id: string; name: string | null; email: string; account_status: string; lastLoginAt: string | null };
type Child = { id: string; name?: string; grade_level?: number };
const initials = (value?: string | null) => (value || '?').split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase();

export default function ParentMonitoringReference({ users, selected, selectedId, onSelect, loading, children, formatDate }: { users: Parent[]; selected: Parent | null; selectedId: string | null; onSelect: (id: string) => void; loading: boolean; children: Child[]; formatDate: (value?: string | null) => string }) {
  const activeParents = users.filter((user) => user.account_status === 'active').length;
  const cards = [[users.length, 'Total Parents', '👥'], [children.length, 'Linked Students', '🔗'], [activeParents, 'Active Parents', '◷'], [0, 'Notifications Sent', '✉']];
  return <div className="parent-monitoring-page mx-auto w-full max-w-[1500px] pb-8">
    <section className="parent-monitoring-hero relative overflow-hidden rounded-3xl border p-6 shadow-card sm:p-8"><img src={parentHero} alt="" aria-hidden="true" /><img src={mascot} alt="" aria-hidden="true" className="parent-hero-mascot" /><div><p>Parents</p><h1>Parents</h1><span>View and manage parents, their activity, and their linked students.</span></div></section>
    <section className="parent-stat-grid mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4">{cards.map(([value, label, icon]) => <article key={String(label)}><span>{icon}</span><div><b>{value}</b><small>{label}</small></div><i>›</i></article>)}</section>
    <div className="parent-reference-grid mt-4 grid gap-4 xl:grid-cols-[20rem_minmax(0,1fr)_20rem]">
      <aside className="parent-directory rounded-3xl border bg-white p-4 shadow-card"><h2>Parent List</h2><p>Select a parent to view their linked students.</p><div>{loading && <p>Loading parents…</p>}{users.map((parent) => <button key={parent.id} type="button" onClick={() => onSelect(parent.id)} className={selectedId === parent.id ? 'selected' : ''}><span>{initials(parent.name || parent.email)}</span><div><b>{parent.name || parent.email}</b><small>{parent.email}</small></div><i className={parent.account_status === 'active' ? 'online' : 'away'} /></button>)}{!loading && !users.length && <p>No parents yet.</p>}</div></aside>
      <main className="min-w-0 space-y-4">{!selected ? <section className="grid min-h-80 place-items-center rounded-3xl border bg-white text-sm text-[var(--color-text-muted)] shadow-card">Select a parent to view details.</section> : <><section className="parent-profile-card rounded-3xl border bg-white p-5 shadow-card"><span>{initials(selected.name || selected.email)}</span><div><h2>{selected.name || selected.email}</h2><p>Parent / Guardian <em>{selected.account_status === 'active' ? 'Active' : 'Inactive'}</em></p><small>Email: {selected.email}<br />Last active: {formatDate(selected.lastLoginAt)}</small></div></section><section className="parent-linked-card rounded-3xl border bg-white p-5 shadow-card"><header><div><p>Family connection</p><h2>Linked Students</h2></div><b>{children.length}</b></header><div className="parent-linked-list">{children.map((child) => <article key={child.id}><span>{initials(child.name)}</span><div><b>{child.name || 'Student'}</b><small>Grade {child.grade_level ?? '--'}</small></div><em>Linked</em><i>›</i></article>)}{!children.length && <p className="parent-empty">No students are linked to this parent yet.</p>}</div></section><section className="parent-activity-card rounded-3xl border bg-white p-5 shadow-card"><header><h2>Recent Parent Activity</h2><span>{selected.lastLoginAt ? 'Last login recorded' : 'No activity recorded'}</span></header>{selected.lastLoginAt && <article><span>↗</span><div><b>Logged in to the system</b><small>{formatDate(selected.lastLoginAt)}</small></div></article>}</section></>}</main>
      <aside className="parent-info-column space-y-4"><section className="parent-info-card rounded-3xl border bg-white p-5 shadow-card"><h2>Parent Information</h2>{selected ? <dl><div><dt>Full name</dt><dd>{selected.name || '--'}</dd></div><div><dt>Email</dt><dd>{selected.email}</dd></div><div><dt>Role</dt><dd>Parent</dd></div><div><dt>Status</dt><dd><i />{selected.account_status === 'active' ? 'Active' : 'Inactive'}</dd></div><div><dt>Linked students</dt><dd>{children.length}</dd></div></dl> : <p>Select a parent to view details.</p>}</section><section className="parent-engagement-card rounded-3xl border bg-white p-5 shadow-card"><h2>Parent Engagement</h2><div className="parent-engagement-ring"><b>{children.length ? '—' : '0%'}</b><small>Engagement</small></div><ul><li><span>✓</span><b>{selected?.lastLoginAt ? 1 : 0}<small>Login recorded</small></b></li><li><span>▥</span><b>0<small>Progress viewed</small></b></li><li><span>✉</span><b>0<small>Notices viewed</small></b></li></ul></section></aside>
    </div>
  </div>;
}
