import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api } from '../../lib/api';
import { cardStyle } from '../../lib/cardStyle';

type Role = 'student' | 'parent' | 'teacher';
type Activity = { id: string; action: string; module: string; status: string; created_at: string; metadata: { platform?: string } };
type MonitoredUser = { id: string; name: string | null; email: string; account_status: string; lastLoginAt: string | null; profile: { gradeLevel?: number | null; children?: { id: string; name: string; gradeLevel: number | null }[] }; activities: Activity[] };
const COPY: Record<Role, { title: string; singular: string; intro: string }> = {
  student: { title: 'Mga Mag-aaral', singular: 'mag-aaral', intro: 'Profile, progreso, at mga aktibidad sa Student modules.' },
  parent: { title: 'Mga Magulang', singular: 'magulang', intro: 'Mga parent account at aktibidad sa Parent modules.' },
  teacher: { title: 'Mga Guro', singular: 'guro', intro: 'Mga teacher account at aktibidad sa Teacher modules.' },
};
const time = (value: string) => new Intl.DateTimeFormat('fil-PH', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Manila' }).format(new Date(value));

export default function RoleMonitoring({ role }: { role: Role }) {
  const [search, setSearch] = useState(''); const [selectedId, setSelectedId] = useState<string | null>(null);
  const query = useQuery({ queryKey: ['admin-role-monitoring', role], queryFn: () => api<{ users: MonitoredUser[] }>(`/admin/monitoring/users?role=${role}`, { auth: true }) });
  const users = useMemo(() => { const q = search.trim().toLowerCase(); return (query.data?.users || []).filter((user) => !q || `${user.name} ${user.email}`.toLowerCase().includes(q)); }, [query.data, search]);
  const selected = users.find((user) => user.id === selectedId) || query.data?.users.find((user) => user.id === selectedId) || null;
  const copy = COPY[role];
  return <div className="mx-auto flex w-full max-w-[1500px] flex-col gap-5 pb-8">
    <header className="rounded-3xl border p-5 shadow-card sm:p-7" style={cardStyle('--color-brand-lavender', 7, 26)}><p className="text-xs font-extrabold tracking-[.14em] text-[var(--color-primary)] uppercase">Role monitoring</p><h1 className="mt-2 text-2xl font-extrabold sm:text-3xl">{copy.title}</h1><p className="mt-1 text-sm text-[var(--color-text-muted)]">{copy.intro} Read-only ito at hindi nagpapakita ng password o authentication data.</p></header>
    <section className="grid gap-5 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)]"><div className="overflow-hidden rounded-3xl border bg-white/65 shadow-card"><div className="border-b p-4"><label className="sr-only" htmlFor="role-search">Maghanap</label><input id="role-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder={`Maghanap ng ${copy.singular}...`} className="min-h-11 w-full rounded-xl border border-[var(--color-border)] bg-white px-3 text-sm" /></div>{query.error ? <p role="alert" className="p-5 text-[var(--color-danger)]">Hindi ma-load ang monitoring data.</p> : <ul className="max-h-[65vh] divide-y overflow-auto">{query.isLoading ? Array.from({ length: 5 }, (_, index) => <li key={index} className="m-4 h-16 animate-pulse rounded-2xl bg-[var(--color-primary-soft)]" />) : users.map((user) => <li key={user.id}><button type="button" onClick={() => setSelectedId(user.id)} className={`w-full p-4 text-left transition hover:bg-[var(--color-primary-soft)]/30 ${selected?.id === user.id ? 'bg-[var(--color-primary-soft)]/50' : ''}`}><span className="flex items-center justify-between gap-3"><span className="min-w-0"><b className="block truncate">{user.name || user.email}</b><small className="block truncate text-[var(--color-text-muted)]">{user.email}</small></span><span className="rounded-full bg-[var(--color-success-soft)] px-2 py-1 text-xs font-bold text-[var(--color-success)]">{user.account_status}</span></span></button></li>)}{!query.isLoading && !users.length && <li className="p-10 text-center text-sm text-[var(--color-text-muted)]">Walang tumugmang account.</li>}</ul>}</div>
      <article className="min-h-[24rem] rounded-3xl border p-5 shadow-card" style={cardStyle('--color-brand-sage', 5, 22)}>{selected ? <><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold tracking-wide text-[var(--color-text-muted)] uppercase">Selected {copy.singular}</p><h2 className="text-xl font-extrabold">{selected.name || selected.email}</h2><p className="text-sm text-[var(--color-text-muted)]">Huling login: {selected.lastLoginAt ? time(selected.lastLoginAt) : 'Wala pa'}</p></div>{role === 'student' && <span className="rounded-full bg-white/70 px-3 py-1 text-sm font-bold">Grade {selected.profile.gradeLevel ?? '—'}</span>}</div>{role === 'parent' && <p className="mt-4 rounded-2xl bg-white/60 p-3 text-sm"><b>Mga anak:</b> {selected.profile.children?.length ? selected.profile.children.map((child) => `${child.name} (Grade ${child.gradeLevel ?? '—'})`).join(', ') : 'Wala pang naka-link na profile.'}</p>}<div className="mt-5"><h3 className="font-extrabold">Kamakailang aktibidad</h3><ul className="mt-2 divide-y rounded-2xl border bg-white/55">{selected.activities.map((activity) => <li key={activity.id} className="p-3"><div className="flex flex-wrap justify-between gap-2"><b className="text-sm">{activity.action.replace('.', ' · ')}</b><span className="text-xs text-[var(--color-text-muted)]">{time(activity.created_at)}</span></div><p className="mt-1 text-xs text-[var(--color-text-muted)]">Module: {activity.module} · Status: {activity.status}{activity.metadata?.platform ? ` · ${activity.metadata.platform}` : ''}</p></li>)}{!selected.activities.length && <li className="p-5 text-sm text-[var(--color-text-muted)]">Wala pang recorded activity.</li>}</ul></div></> : <div className="grid h-full place-items-center text-center text-sm text-[var(--color-text-muted)]">Pumili ng account upang makita ang profile at aktibidad.</div>}</article></section>
  </div>;
}
