import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import studentHero from '../../assets/admin_design/admin-hero-background.png';
import studentMascot from '../../assets/admin_design/owl-admin-mascot.png';
import { api } from '../../lib/api';

type User = { id: string; name: string | null; email: string; account_status: string; lastLoginAt: string | null; profile: { gradeLevel?: number | null } };
type Module = { id: string; title?: string; module_number?: number; state?: 'completed' | 'in_progress' | 'not_started' | 'locked' };
type Activity = { id: string; title: string; meta: string };
type Progress = { activities_completed?: number; updated_at?: string };
type StudentNote = { id: string; content: string; created_at: string };

const initials = (value?: string | null) => (value || '?').split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase();
const moduleState = (value?: Module['state']) => value === 'completed' ? 'Completed' : value === 'in_progress' ? 'In progress' : value === 'locked' ? 'Locked' : 'Not started';
const stateClass = (value?: Module['state']) => value === 'completed' ? 'student-state-complete' : value === 'in_progress' ? 'student-state-progress' : value === 'locked' ? 'student-state-locked' : 'student-state-new';
const MODULES_PER_PAGE = 4;

export default function StudentMonitoringReference({ users, selected, selectedId, onSelect, loading, modules, learning, progress, completed, overall, average, formatDate }: {
  users: User[]; selected: User | null; selectedId: string | null; onSelect: (id: string) => void; loading: boolean; modules: Module[]; learning: Activity[]; progress?: Progress; completed: number; overall: number; average: number | null; formatDate: (value?: string | null) => string;
}) {
  const [modulePage, setModulePage] = useState(1);
  const [activityModalOpen, setActivityModalOpen] = useState(false);
  const [noteDraft, setNoteDraft] = useState('');
  const [noteError, setNoteError] = useState<string | null>(null);
  const queryClient = useQueryClient();
  const notes = useQuery({ queryKey: ['admin-student-notes', selectedId], queryFn: () => api<{ notes: StudentNote[] }>(`/admin/monitoring/users/${selectedId}/notes`, { auth: true }), enabled: Boolean(selectedId) });
  const refreshNotes = () => queryClient.invalidateQueries({ queryKey: ['admin-student-notes', selectedId] });
  const addNote = useMutation({ mutationFn: () => api<{ note: StudentNote }>(`/admin/monitoring/users/${selectedId}/notes`, { method: 'POST', auth: true, body: { content: noteDraft } }), onSuccess: () => { setNoteDraft(''); setNoteError(null); refreshNotes(); }, onError: (error: Error) => setNoteError(error.message) });
  const deleteNote = useMutation({ mutationFn: (noteId: string) => api(`/admin/monitoring/users/${selectedId}/notes/${noteId}`, { method: 'DELETE', auth: true }), onSuccess: refreshNotes, onError: (error: Error) => setNoteError(error.message) });
  const activeStudents = users.filter((user) => user.account_status === 'active').length;
  const needsSupport = users.length - activeStudents;
  const totalModulePages = Math.max(1, Math.ceil(modules.length / MODULES_PER_PAGE));
  const visibleModules = modules.slice((modulePage - 1) * MODULES_PER_PAGE, modulePage * MODULES_PER_PAGE);
  useEffect(() => setModulePage(1), [selectedId]);
  useEffect(() => { setNoteDraft(''); setNoteError(null); }, [selectedId]);
  useEffect(() => setModulePage((page) => Math.min(page, totalModulePages)), [totalModulePages]);
  const metricCards = [[users.length, 'Total Students', '👥'], [activeStudents, 'Active Students', '🎓'], [needsSupport, 'Need Attention', '▥'], [completed, 'Completed Modules', '🏆']];

  return <div className="student-monitoring-page student-reference-page mx-auto w-full max-w-[1500px] pb-8">
    <section className="student-monitoring-hero relative overflow-hidden rounded-3xl border p-6 shadow-card sm:p-8">
      <img src={studentHero} alt="" aria-hidden="true" className="student-monitoring-hero-bg" />
      <img src={studentMascot} alt="" aria-hidden="true" className="student-monitoring-mascot" />
      <div className="relative z-10 max-w-xl"><p className="text-xs font-extrabold tracking-[.14em] text-[var(--color-primary)] uppercase">Students</p><h1 className="mt-2 text-3xl font-extrabold sm:text-4xl">Students</h1><p className="mt-2 text-sm leading-relaxed text-[#28596a] sm:text-base">View and manage student accounts, their progress, and learning details.</p></div>
    </section>
    <section aria-label="Student statistics" className="student-stat-grid mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4">{metricCards.map(([value, label, icon]) => <article key={String(label)} className="student-stat-card"><span>{icon}</span><div><b>{value}</b><small>{label}</small></div><i>›</i></article>)}</section>
    <div className="student-reference-grid mt-4 grid gap-4 xl:grid-cols-[20rem_minmax(0,1fr)_20rem]">
      <aside className="student-directory rounded-3xl border bg-white p-4 shadow-card"><h2>Student List</h2><p className="student-directory-caption">Select a student to view their learning details.</p><div className="student-directory-list mt-3 max-h-[36rem] space-y-1 overflow-y-auto pr-1">{loading && <p className="p-3 text-sm text-[var(--color-text-muted)]">Loading students...</p>}{users.map((user) => <button key={user.id} type="button" onClick={() => onSelect(user.id)} className={selectedId === user.id ? 'selected' : ''}><span>{initials(user.name || user.email)}</span><div><b>{user.name || user.email}</b><small>Grade {user.profile.gradeLevel ?? '--'}</small></div><i className={user.account_status === 'active' ? 'online' : 'away'} /></button>)}{!loading && !users.length && <p className="p-3 text-sm text-[var(--color-text-muted)]">No students yet.</p>}</div></aside>
      <main className="min-w-0 space-y-4">{!selected ? <section className="grid min-h-80 place-items-center rounded-3xl border bg-white text-sm text-[var(--color-text-muted)] shadow-card">Select a student to view details.</section> : <><section className="student-profile-card rounded-3xl border bg-white p-5 shadow-card"><span className="student-profile-avatar">{initials(selected.name || selected.email)}</span><div><h2>{selected.name || selected.email}</h2><p>Grade {selected.profile.gradeLevel ?? '--'} <em>{selected.account_status === 'active' ? 'Active' : 'Inactive'}</em></p><small>Email: {selected.email}<br />Last active: {formatDate(selected.lastLoginAt || progress?.updated_at)}</small></div></section><section className="student-progress-card rounded-3xl border bg-white p-5 shadow-card"><div className="student-progress-summary"><div className="student-progress-ring" style={{ '--student-progress': `${overall * 3.6}deg` } as React.CSSProperties}><div><b>{overall || '—'}{overall ? '%' : ''}</b><small>progress</small></div></div><div><h2>Overall Progress</h2><p>Learning progress across available modules.</p><div className="student-mini-metrics"><span><b>{completed}</b><small>Completed</small></span><span><b>{progress?.activities_completed ?? 0}</b><small>Activities</small></span><span><b>{average === null ? '—' : `${average}%`}</b><small>Accuracy</small></span></div></div></div><h3>Module Progress</h3><div className="student-module-list">{visibleModules.map((module, index) => <article key={module.id}><span>{module.module_number || (modulePage - 1) * MODULES_PER_PAGE + index + 1}</span><div><b>{module.title || 'Module'}</b><small>{moduleState(module.state)}</small></div><em className={stateClass(module.state)}>{moduleState(module.state)}</em><i>›</i></article>)}{!modules.length && <p className="text-sm text-[var(--color-text-muted)]">No module progress is available yet.</p>}</div>{modules.length > MODULES_PER_PAGE && <footer className="student-module-pagination"><button type="button" onClick={() => setModulePage((page) => Math.max(1, page - 1))} disabled={modulePage === 1}>← Previous</button><span>Page {modulePage} of {totalModulePages}</span><button type="button" onClick={() => setModulePage((page) => Math.min(totalModulePages, page + 1))} disabled={modulePage === totalModulePages}>Next →</button></footer>}</section></>}</main>
      <aside className="student-side-column space-y-4"><section className="student-activity-card rounded-3xl border bg-white p-5 shadow-card"><header><div><p>Recent Activity</p><h2>Learning Activity</h2></div><button type="button" onClick={() => setActivityModalOpen(true)}>View all →</button></header><div className="student-activity-list">{learning.slice(0, 5).map((item, index) => <article key={item.id}><span>{['✓', '▣', '★', '↗', '●'][index]}</span><div><b>{item.title}</b><small>{item.meta}</small></div></article>)}{!learning.length && <p className="rounded-2xl border border-dashed p-4 text-sm text-[var(--color-text-muted)]">No learning activity yet.</p>}</div></section><section className="student-notes-card rounded-3xl border bg-white p-5 shadow-card"><h2>Student Notes</h2>{selected ? <><form onSubmit={(event) => { event.preventDefault(); if (noteDraft.trim()) addNote.mutate(); }}><label className="sr-only" htmlFor="student-note">Add a note</label><textarea id="student-note" value={noteDraft} onChange={(event) => setNoteDraft(event.target.value)} maxLength={1000} placeholder="Write a private note..." /><button type="submit" disabled={!noteDraft.trim() || addNote.isPending}>{addNote.isPending ? 'Saving…' : '+ Add note'}</button></form>{noteError && <p className="student-note-error">{noteError}</p>}<div className="student-note-list">{notes.isLoading && <p>Loading notes…</p>}{notes.data?.notes.map((note) => <article key={note.id}><p>{note.content}</p><footer><time>{formatDate(note.created_at)}</time><button type="button" aria-label="Delete note" onClick={() => deleteNote.mutate(note.id)} disabled={deleteNote.isPending}>Delete</button></footer></article>)}{!notes.isLoading && !notes.data?.notes.length && <p className="student-notes-empty">No notes yet for this student.</p>}</div></> : <p className="student-notes-empty">Select a student to manage notes.</p>}</section></aside>
    </div>
    {activityModalOpen && <div className="student-activity-modal" role="dialog" aria-modal="true" aria-labelledby="all-activity-title" onMouseDown={() => setActivityModalOpen(false)}><section onMouseDown={(event) => event.stopPropagation()}><header><div><p>Student activity</p><h2 id="all-activity-title">All Learning Activity</h2></div><button type="button" aria-label="Close activity modal" onClick={() => setActivityModalOpen(false)}>×</button></header><div className="student-activity-list">{learning.map((item, index) => <article key={item.id}><span>{['✓', '▣', '★', '↗', '●'][index % 5]}</span><div><b>{item.title}</b><small>{item.meta}</small></div></article>)}{!learning.length && <p className="rounded-2xl border border-dashed p-4 text-sm text-[var(--color-text-muted)]">No learning activity yet.</p>}</div></section></div>}
  </div>;
}
