
type Teacher = { id: string; name: string | null; email: string; account_status: string; lastLoginAt: string | null };
type Roster = { student_id: string; assigned_at: string };
type Material = { id: string; title?: string; grade_level?: number; level?: string; created_at: string };
type Assignment = { id: string; student_id?: string; status?: string; assigned_at?: string };
const initials = (value?: string | null) => (value || '?').split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase();

export default function TeacherMonitoringReference({ users, selected, selectedId, onSelect, loading, roster, materials, assignments, formatDate }: { users: Teacher[]; selected: Teacher | null; selectedId: string | null; onSelect: (id: string) => void; loading: boolean; roster: Roster[]; materials: Material[]; assignments: Assignment[]; formatDate: (value?: string | null) => string }) {
  const activeTeachers = users.filter((teacher) => teacher.account_status === 'active').length;
  const gradeLevels = [...new Set(materials.map((item) => item.grade_level).filter(Boolean))];
  const cards = [[users.length, 'Total Teachers', '👥'], [activeTeachers, 'Active Teachers', '📖'], [0, 'On Leave', '◷'], [assignments.length, 'Assignments Created', '👤']];
  return <div className="teacher-monitoring-page mx-auto w-full max-w-[1500px] pb-8">
    <div className="teacher-reference-grid grid gap-4 xl:grid-cols-[20rem_minmax(0,1fr)_20rem]">
      <aside className="teacher-directory rounded-3xl border bg-white p-4 shadow-card"><header><h2>Teachers</h2><span>{users.length}</span></header><p>Select a teacher to view their teaching details.</p><div>{loading && <p>Loading teachers…</p>}{users.map((teacher) => <button key={teacher.id} type="button" onClick={() => onSelect(teacher.id)} className={selectedId === teacher.id ? 'selected' : ''}><span>{initials(teacher.name || teacher.email)}</span><div><b>{teacher.name || teacher.email}</b><small>{teacher.email}</small></div><i className={teacher.account_status === 'active' ? 'online' : 'away'} /></button>)}{!loading && !users.length && <p>No teachers yet.</p>}</div></aside>
      <main className="min-w-0 space-y-4"><section className="teacher-overview-card rounded-3xl border bg-white p-5 shadow-card"><h2>Teacher Overview</h2><div>{cards.map(([value, label, icon]) => <article key={String(label)}><span>{icon}</span><b>{value}</b><small>{label}</small></article>)}</div></section>{!selected ? <section className="grid min-h-80 place-items-center rounded-3xl border bg-white text-sm text-[var(--color-text-muted)] shadow-card">Select a teacher to view details.</section> : <><section className="teacher-profile-card rounded-3xl border bg-white p-5 shadow-card"><span>{initials(selected.name || selected.email)}</span><div><h2>{selected.name || selected.email} <em>{selected.account_status === 'active' ? 'Active' : 'Inactive'}</em></h2><p>Teacher {gradeLevels.length ? `• Grade ${gradeLevels.join(', ')}` : ''}</p><small>Email: {selected.email}<br />Last active: {formatDate(selected.lastLoginAt)}</small></div><b>{roster.length}<small>Students handled</small></b></section><section className="teacher-classes-card rounded-3xl border bg-white p-5 shadow-card"><header><h2>Classes and Students</h2><span>{roster.length} students</span></header><div>{gradeLevels.length ? gradeLevels.map((grade, index) => <article key={grade}><span>{['👥', '👥', '👥'][index % 3]}</span><b>Grade {grade}</b><small>{index === 0 ? roster.length : 0} students</small><i>›</i></article>) : <p className="teacher-empty">No classes are recorded for this teacher yet.</p>}</div></section><section className="teacher-materials-card rounded-3xl border bg-white p-5 shadow-card"><header><h2>Recent Learning Materials</h2><span>{materials.length} total</span></header><div>{materials.slice(0, 4).map((material, index) => <article key={material.id}><span>{['▣', '▤', '▧', '▥'][index % 4]}</span><div><b>{material.title || 'Untitled material'}</b><small>{material.grade_level ? `Grade ${material.grade_level}` : material.level || 'Learning material'} • {formatDate(material.created_at)}</small></div><i>›</i></article>)}{!materials.length && <p className="teacher-empty">No learning materials yet.</p>}</div></section></>}</main>
      <aside className="teacher-info-column space-y-4"><section className="teacher-info-card rounded-3xl border bg-white p-5 shadow-card"><h2>Teacher Information</h2>{selected ? <dl><div><dt>Full name</dt><dd>{selected.name || '--'}</dd></div><div><dt>Email</dt><dd>{selected.email}</dd></div><div><dt>Role</dt><dd>Teacher</dd></div><div><dt>Grade levels</dt><dd>{gradeLevels.length ? gradeLevels.join(', ') : '--'}</dd></div><div><dt>Students handled</dt><dd>{roster.length}</dd></div><div><dt>Status</dt><dd><i />{selected.account_status === 'active' ? 'Active' : 'Inactive'}</dd></div></dl> : <p>Select a teacher to view details.</p>}</section><section className="teacher-activity-card rounded-3xl border bg-white p-5 shadow-card"><header><h2>Recent Activity</h2><span>Latest records</span></header><div>{selected?.lastLoginAt && <article><span>♟</span><div><b>Logged in to the system</b><small>{formatDate(selected.lastLoginAt)}</small></div></article>}{materials.slice(0, 2).map((material) => <article key={material.id}><span>▣</span><div><b>Created learning material</b><small>{material.title || 'Untitled material'} • {formatDate(material.created_at)}</small></div></article>)}{assignments.slice(0, 2).map((assignment) => <article key={assignment.id}><span>▤</span><div><b>Created assignment</b><small>{assignment.status || 'Assigned'} • {formatDate(assignment.assigned_at)}</small></div></article>)}{!selected?.lastLoginAt && !materials.length && !assignments.length && <p className="teacher-empty">No activity recorded yet.</p>}</div></section></aside>
    </div>
  </div>;
}
