import { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { api } from '../../lib/api';
import { cardStyle, CARD_COLORS } from '../../lib/cardStyle';

interface UserRow { id: string; email: string; name: string | null; role: string; account_status: string; created_at: string }
const GRADES = [1, 2, 3, 4, 5, 6];
const inputClass = 'min-h-11 w-full rounded-xl border border-[var(--color-border)] bg-white/75 px-4 outline-none transition focus:border-[var(--color-primary)] focus:ring-2 focus:ring-[var(--color-primary)]/15';

export default function AdminTeachers() {
  const [email, setEmail] = useState(''); const [name, setName] = useState(''); const [gradeLevels, setGradeLevels] = useState<number[]>([]); const [error, setError] = useState<string | null>(null); const [created, setCreated] = useState<{ email: string } | null>(null);
  const { data, refetch, isLoading } = useQuery({ queryKey: ['admin-users', 'teacher', ''], queryFn: () => api<{ users: UserRow[] }>('/admin/users?role=teacher', { auth: true }) });
  const createTeacher = useMutation({ mutationFn: () => api<{ success: true; teacherId: string }>('/admin/teachers', { method: 'POST', auth: true, body: { email, name, gradeLevels } }), onSuccess: () => { setCreated({ email }); setEmail(''); setName(''); setGradeLevels([]); setError(null); refetch(); }, onError: (err: Error) => setError(err.message) });
  const toggleGrade = (grade: number) => setGradeLevels((current) => current.includes(grade) ? current.filter((item) => item !== grade) : [...current, grade].sort());
  const teachers = data?.users ?? [];
  return <div className="flex min-w-0 flex-col gap-6">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-extrabold tracking-[.12em] text-[var(--color-primary)] uppercase">Faculty accounts</p><h1 className="text-2xl font-extrabold sm:text-3xl">Mga Guro</h1><p className="mt-1 text-sm text-[var(--color-text-muted)]">Gumawa ng teacher account at italaga ang sakop na baitang.</p></div>{data && <div className="rounded-2xl border px-4 py-2 text-center shadow-card" style={cardStyle('--color-brand-sun', 7, 25)}><p className="text-2xl font-extrabold">{teachers.length}</p><p className="text-xs font-bold text-[var(--color-text-muted)]">Mga guro</p></div>}</header>
    <div className="grid min-w-0 grid-cols-1 gap-5 xl:grid-cols-5">
      <form onSubmit={(event) => { event.preventDefault(); setError(null); setCreated(null); if (!gradeLevels.length) { setError('Pumili ng kahit isang grade level.'); return; } createTeacher.mutate(); }} className="rounded-3xl border p-5 shadow-card sm:p-6 xl:col-span-2" style={cardStyle('--color-brand-sun', 7, 26)}><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-white/70 text-xl">＋</span><div><h2 className="text-xl font-extrabold">Bagong teacher account</h2><p className="text-xs text-[var(--color-text-muted)]">Lahat ng field ay kinakailangan.</p></div></div><div className="mt-5 flex flex-col gap-4"><label className="text-sm font-bold" htmlFor="teacher-name">Buong pangalan<input id="teacher-name" value={name} onChange={(event) => setName(event.target.value)} required className={`${inputClass} mt-1.5 font-normal`} placeholder="Hal. Maria Santos" /></label><label className="text-sm font-bold" htmlFor="teacher-email">Email address<input id="teacher-email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} required className={`${inputClass} mt-1.5 font-normal`} placeholder="guro@paaralan.edu.ph" /></label><fieldset><legend className="text-sm font-bold">Mga baitang</legend><p className="mt-0.5 text-xs text-[var(--color-text-muted)]">Piliin ang lahat ng hahawakang grade level.</p><div className="mt-2 grid grid-cols-3 gap-2">{GRADES.map((grade) => <button key={grade} type="button" onClick={() => toggleGrade(grade)} aria-pressed={gradeLevels.includes(grade)} className={`min-h-11 rounded-xl border text-sm font-extrabold transition-all ${gradeLevels.includes(grade) ? 'border-[var(--color-primary)] bg-[var(--color-primary)] text-white shadow-card' : 'border-[var(--color-border)] bg-white/60 hover:border-[var(--color-primary)]'}`}>Grade {grade}</button>)}</div></fieldset>{error && <p role="alert" className="rounded-xl bg-[var(--color-danger-soft)] p-3 text-sm font-bold text-[var(--color-danger)]">{error}</p>}<button type="submit" disabled={createTeacher.isPending} className="min-h-12 rounded-xl bg-[var(--color-primary)] px-5 text-sm font-extrabold text-white shadow-card transition-transform hover:-translate-y-0.5 disabled:opacity-50">{createTeacher.isPending ? 'Ginagawa ang account...' : '＋ Gumawa ng Account'}</button></div></form>
      <section className="min-w-0 rounded-3xl border p-5 shadow-card sm:p-6 xl:col-span-3" style={cardStyle('--color-brand-lavender', 5, 22)}><div><p className="text-xs font-bold tracking-wide text-[var(--color-brand-violet)] uppercase">Directory</p><h2 className="text-xl font-extrabold">Kasalukuyang mga guro</h2></div>{isLoading ? <p className="mt-5 text-sm text-[var(--color-text-muted)]">Naglo-load...</p> : teachers.length ? <ul className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2">{teachers.map((teacher, index) => <li key={teacher.id} className="flex min-w-0 items-center gap-3 rounded-2xl border p-3" style={cardStyle(CARD_COLORS[index % CARD_COLORS.length], 4, 18)}><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-white/70 text-lg">🎓</span><span className="min-w-0 flex-1"><span className="block truncate font-extrabold">{teacher.name ?? 'Walang pangalan'}</span><span className="block truncate text-xs text-[var(--color-text-muted)]">{teacher.email}</span></span><span className={`h-2.5 w-2.5 shrink-0 rounded-full ${teacher.account_status === 'active' ? 'bg-[var(--color-success)]' : 'bg-[var(--color-warning)]'}`} title={teacher.account_status} /></li>)}</ul> : <div className="mt-5 rounded-2xl border border-dashed border-[var(--color-border)] bg-white/40 p-8 text-center"><p className="text-3xl">🎓</p><p className="mt-2 font-extrabold">Wala pang guro</p><p className="text-sm text-[var(--color-text-muted)]">Gamitin ang form para gumawa ng unang account.</p></div>}</section>
    </div>
    {created && <div role="status" className="flex items-start gap-3 rounded-3xl border border-[var(--color-success)]/35 bg-[var(--color-success-soft)] p-4 shadow-card"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-white/70 text-[var(--color-success)]">✓</span><div><p className="font-extrabold">Nagawa ang account para kay {created.email}</p><p className="mt-1 text-sm text-[var(--color-text-muted)]">Naipadala na ang pansamantalang password sa email ng guro.</p></div></div>}
  </div>;
}
