import { useMemo, useState } from 'react';
import { BookOpen, CalendarDays, ChevronLeft, ChevronRight, Clock3, FileText, GraduationCap, Mail, MoreHorizontal, Plus, Search, UserPlus, UsersRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import heroBackground from '../../assets/teacher/Teacher Home Hero Banner Background.png';
import teacherMascot from '../../assets/teacher/Teacher Illustration.png';

type Teacher = { id: string; name: string | null; email: string; account_status: string; lastLoginAt: string | null; created_at?: string; profile?: { gradeLevels?: number[] } };
type Roster = { student_id: string; assigned_at: string };
type Material = { id: string; title?: string; grade_level?: number; level?: string; created_at: string };
type Assignment = { id: string; student_id?: string; status?: string; assigned_at?: string };
type Section = { id: string; name: string; grade_level: number; is_reading_support: boolean; studentCount: number };
type Activity = { id: string; action: string; module?: string; created_at: string };

const initials = (value?: string | null) => (value || '?').split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase();
const nameFor = (teacher: Teacher) => teacher.name || teacher.email;
const statusLabel = (status: string) => status === 'active' ? 'Active' : status === 'disabled' ? 'Disabled' : status;
const activityLabel = (activity: Activity) => activity.action.replaceAll(/[._]/g, ' ').toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase());

export default function TeacherMonitoringReference({ users, selected, selectedId, onSelect, loading, roster, materials, assignments, sections, activity, formatDate }: { users: Teacher[]; selected: Teacher | null; selectedId: string | null; onSelect: (id: string) => void; loading: boolean; roster: Roster[]; materials: Material[]; assignments: Assignment[]; sections: Section[]; activity: Activity[]; formatDate: (value?: string | null) => string }) {
  const [search, setSearch] = useState(''); const [grade, setGrade] = useState(''); const [status, setStatus] = useState('');
  const activeTeachers = users.filter((teacher) => teacher.account_status === 'active').length;
  const monthStart = new Date(); monthStart.setDate(1); monthStart.setHours(0, 0, 0, 0);
  const newAccounts = users.filter((teacher) => teacher.created_at && new Date(teacher.created_at) >= monthStart).length;
  const grades = selected?.profile?.gradeLevels || [];
  const gradeOptions = [...new Set(users.flatMap((teacher) => teacher.profile?.gradeLevels || []))].sort((a, b) => a - b);
  const visibleTeachers = useMemo(() => users.filter((teacher) => `${teacher.name || ''} ${teacher.email}`.toLowerCase().includes(search.toLowerCase()) && (!grade || teacher.profile?.gradeLevels?.includes(Number(grade))) && (!status || teacher.account_status === status)), [users, search, grade, status]);
  const stats = [{ label: 'Total Teachers', value: users.length, note: 'Registered accounts', icon: <UsersRound /> }, { label: 'Active Teachers', value: activeTeachers, note: 'Available accounts', icon: <BookOpen /> }, { label: 'On Leave', value: '—', note: 'Not tracked', icon: <Clock3 /> }, { label: 'New Accounts', value: newAccounts, note: 'Created this month', icon: <UserPlus /> }];
  const classes = sections.length ? sections : grades.map((gradeLevel) => ({ id: `grade-${gradeLevel}`, name: `Grade ${gradeLevel}`, grade_level: gradeLevel, is_reading_support: false, studentCount: 0 }));
  const activityItems = [...activity.slice(0, 4).map((item) => ({ id: item.id, title: activityLabel(item), meta: formatDate(item.created_at), kind: 'audit' })), ...materials.slice(0, 2).map((item) => ({ id: `material-${item.id}`, title: 'Created learning material', meta: `${item.title || 'Untitled material'} · ${formatDate(item.created_at)}`, kind: 'material' })), ...assignments.slice(0, 2).map((item) => ({ id: `assignment-${item.id}`, title: 'Created an assignment', meta: formatDate(item.assigned_at), kind: 'assignment' }))].slice(0, 5);

  return <div className="teacher-dashboard">
    <section className="teacher-dashboard__hero"><img src={heroBackground} alt="" aria-hidden="true" /><img className="teacher-dashboard__mascot" src={teacherMascot} alt="" aria-hidden="true" /><div><p>Teacher Management</p><h1>Support our<br />Amazing Teachers</h1><span>Pamahalaan ang mga guro, kanilang asignasyon, at subaybayan ang kanilang mga aktibidad.</span></div></section>
    <section className="teacher-dashboard__stats" aria-label="Teacher statistics">{stats.map((item) => <article key={item.label}><span>{item.icon}</span><div><small>{item.label}</small><b>{item.value}</b><em>{item.note}</em></div></article>)}</section>
    <div className="teacher-dashboard__content">
      <section className="teacher-dashboard__directory"><header><span className="teacher-dashboard__heading-icon"><GraduationCap /></span><div><h2>Teachers</h2><p>Listahan ng lahat ng registered na guro.</p></div><Link to="/admin/teachers"><Plus /> Create Teacher Account</Link></header><label className="teacher-dashboard__search"><Search /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Maghanap ng teacher..." /></label><div className="teacher-dashboard__filters"><select value={grade} onChange={(event) => setGrade(event.target.value)} aria-label="Filter by grade"><option value="">Lahat ng Grade</option>{gradeOptions.map((item) => <option key={item} value={item}>Grade {item}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value)} aria-label="Filter by status"><option value="">Lahat ng Status</option><option value="active">Active</option><option value="disabled">Disabled</option></select><select aria-label="Filter by role"><option>Teacher</option></select></div><div className="teacher-dashboard__table-wrap"><table><thead><tr><th>Teacher</th><th>Grade Levels</th><th>Students</th><th>Status</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{loading && <tr><td colSpan={5}>Loading teachers...</td></tr>}{visibleTeachers.map((teacher) => <tr className={teacher.id === selectedId ? 'is-selected' : ''} key={teacher.id} onClick={() => onSelect(teacher.id)}><td><button type="button" className="teacher-dashboard__person"><span>{initials(nameFor(teacher))}</span><i><b>{nameFor(teacher)}</b><small>{teacher.email}</small></i></button></td><td>{teacher.profile?.gradeLevels?.length ? teacher.profile.gradeLevels.map((item) => <em className="teacher-dashboard__grade" key={item}>Grade {item}</em>) : <small>None</small>}</td><td>{teacher.id === selectedId ? roster.length : '—'}</td><td><em className={`teacher-dashboard__status ${teacher.account_status === 'active' ? 'active' : ''}`}>{statusLabel(teacher.account_status)}</em></td><td><button type="button" className="teacher-dashboard__more" aria-label={`Actions for ${nameFor(teacher)}`} onClick={(event) => event.stopPropagation()}><MoreHorizontal /></button></td></tr>)}{!loading && !visibleTeachers.length && <tr><td colSpan={5}>No teachers match these filters.</td></tr>}</tbody></table></div><footer><span>Showing {visibleTeachers.length} of {users.length} teachers</span><nav aria-label="Teacher directory pages"><button disabled><ChevronLeft /></button><button className="current">1</button><button disabled><ChevronRight /></button></nav></footer></section>
      <aside className="teacher-dashboard__aside"><section className="teacher-dashboard__information"><header><span className="teacher-dashboard__heading-icon"><FileText /></span><h2>Teacher Information</h2></header>{selected ? <><div className="teacher-dashboard__profile"><span>{initials(nameFor(selected))}</span><div><h3>{nameFor(selected)} <em className={selected.account_status === 'active' ? 'active' : ''}>{statusLabel(selected.account_status)}</em></h3><small>Teacher</small><small><Mail /> {selected.email}</small><small><CalendarDays /> Last active: {formatDate(selected.lastLoginAt)}</small></div></div><div className="teacher-dashboard__metrics"><article><UsersRound /><b>{roster.length}</b><small>Students Handled</small></article><article><BookOpen /><b>{materials.length}</b><small>Learning Materials</small></article><article><FileText /><b>{assignments.length}</b><small>Assignments Created</small></article><article><Clock3 /><b>—</b><small>Average Progress</small></article></div><dl><div><dt>Full Name</dt><dd>{selected.name || '—'}</dd></div><div><dt>Email</dt><dd>{selected.email}</dd></div><div><dt>Role</dt><dd>Teacher</dd></div><div><dt>Grade Levels</dt><dd>{grades.length ? grades.map((item) => `Grade ${item}`).join(', ') : '—'}</dd></div><div><dt>Sections</dt><dd>{sections.length || '—'}</dd></div><div><dt>Students Handled</dt><dd>{roster.length}</dd></div><div><dt>Status</dt><dd><i className={selected.account_status === 'active' ? 'active' : ''} />{statusLabel(selected.account_status)}</dd></div></dl></> : <p className="teacher-dashboard__empty">Select a teacher to view details.</p>}</section><section className="teacher-dashboard__activity"><header><span className="teacher-dashboard__heading-icon"><Clock3 /></span><h2>Recent Activity</h2></header><div>{activityItems.map((item) => <article key={item.id}><span className={item.kind}><FileText /></span><div><b>{item.title}</b><small>{item.meta}</small></div></article>)}{selected && !activityItems.length && <p className="teacher-dashboard__empty">No activity recorded yet.</p>}</div></section></aside>
      <section className="teacher-dashboard__classes"><header><span className="teacher-dashboard__heading-icon"><BookOpen /></span><div><h2>Classes and Students</h2><p>Mga klase na hinahawakan ng guro.</p></div><span className="teacher-dashboard__view">View all <ChevronRight /></span></header><div>{selected && classes.map((item) => <article key={item.id}><span><GraduationCap /></span><div><b>{item.name}</b><small>{item.is_reading_support ? 'Reading support group · ' : ''}{item.studentCount} student{item.studentCount === 1 ? '' : 's'}</small></div><ChevronRight /></article>)}{selected && !classes.length && <p className="teacher-dashboard__empty">No sections or grade levels assigned yet.</p>}</div></section>
    </div>
  </div>;
}
